/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package p4;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.Shape;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;

/**
 *
 * @author Diego
 */
public class PanelLienzo extends javax.swing.JPanel {

    enum Herramienta{
        Linea, Rectangulo, Elipse
    }
    
    private Shape forma = new Line2D.Float();
    private Color color = Color.black;
    private Boolean relleno = false;
    private Herramienta herramienta;
    private Point punto;

    public Shape getForma() {
        return forma;
    }

    public void setForma(Shape forma) {
        this.forma = forma;
    }

    public Color getColor() {
        return color;
    }

    public void setColor(Color color) {
        this.color = color;
    }

    public Boolean getRelleno() {
        return relleno;
    }

    public void setRelleno(Boolean relleno) {
        this.relleno = relleno;
    }

    public Herramienta getHerramienta() {
        return herramienta;
    }

    public void setHerramienta(Herramienta herramienta) {
        this.herramienta = herramienta;
    }
    
    
    /**
     * Creates new form PanelLienzo
     */
    public PanelLienzo() {
        initComponents();
    }

    @Override
    public void paint(Graphics g){
        super.paint(g);
        Graphics2D g2d = (Graphics2D)g;
        
        g2d.setPaint(color);
        if(relleno){
            g2d.fill(forma);
        }
        
        g2d.draw(forma);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        switch (herramienta) {
            case Linea: 
                forma = new Line2D.Float(evt.getPoint(),evt.getPoint());
                break;
            case Rectangulo:
                forma = new Rectangle2D.Float(evt.getPoint().x,evt.getPoint().y,evt.getPoint().x,evt.getPoint().y);
                break;
                
            case Elipse:
                forma = new Ellipse2D.Float(evt.getPoint().x,evt.getPoint().y,evt.getPoint().x,evt.getPoint().y);
                break;
            default:
                throw new AssertionError();
        }
        punto = evt.getPoint();

    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        if(herramienta == Herramienta.Linea)((Line2D)forma).setLine(((Line2D)forma).getP1(), evt.getPoint());
        if(herramienta == Herramienta.Rectangulo)((Rectangle2D)forma).setFrameFromDiagonal(punto,evt.getPoint());
        if(herramienta == Herramienta.Elipse)((Ellipse2D)forma).setFrameFromDiagonal(punto, evt.getPoint());

        this.repaint();
    }//GEN-LAST:event_formMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
