
package p8;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Stroke;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import sm.dsv.Imagen.PanelLienzo;
import static sm.dsv.Imagen.PanelLienzo.Herramienta.Elipse;
import static sm.dsv.Imagen.PanelLienzo.Herramienta.Fantasma;
import static sm.dsv.Imagen.PanelLienzo.Herramienta.Linea;
import static sm.dsv.Imagen.PanelLienzo.Herramienta.Rectangulo;
import static sm.dsv.Imagen.PanelLienzo.Herramienta.Arrastrar;


/**
 *
 * @author Diego
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    private PanelLienzo getSelectedLienzo() {
        VentanaInterna vi;
        vi = (VentanaInterna)escritorio.getSelectedFrame();
        return vi!=null ? vi.getLienzo2D() : null;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paint = new javax.swing.ButtonGroup();
        colo = new javax.swing.ButtonGroup();
        jColorChooser1 = new javax.swing.JColorChooser();
        PanelToolBar = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        Nuevo = new javax.swing.JButton();
        Abrir = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        BotonLinea = new javax.swing.JToggleButton();
        BotonRectangulo = new javax.swing.JToggleButton();
        BotonElipse = new javax.swing.JToggleButton();
        BotonFantasma = new javax.swing.JToggleButton();
        BotonMover = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        BotonColor = new javax.swing.JButton();
        BotonRelleno = new javax.swing.JToggleButton();
        BotonTransparencia = new javax.swing.JToggleButton();
        BotonAlisar = new javax.swing.JToggleButton();
        Grosor = new javax.swing.JSlider();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        Volcado = new javax.swing.JButton();
        PanelEstado = new javax.swing.JPanel();
        LabelEstado = new javax.swing.JLabel();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        MenuNuevo = new javax.swing.JMenuItem();
        MenuAbrir = new javax.swing.JMenuItem();
        MenuGuardar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelToolBar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jToolBar2.setRollover(true);
        jToolBar2.setBorderPainted(false);

        Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos2/nuevo.png"))); // NOI18N
        Nuevo.setFocusable(false);
        Nuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Nuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });
        jToolBar2.add(Nuevo);

        Abrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos2/abrir.png"))); // NOI18N
        Abrir.setFocusable(false);
        Abrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Abrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirActionPerformed(evt);
            }
        });
        jToolBar2.add(Abrir);

        Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos2/guardar.png"))); // NOI18N
        Guardar.setFocusable(false);
        Guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jToolBar2.add(Guardar);
        jToolBar2.add(jSeparator3);

        paint.add(BotonLinea);
        BotonLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/linea.png"))); // NOI18N
        BotonLinea.setBorderPainted(false);
        BotonLinea.setFocusable(false);
        BotonLinea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonLinea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLineaActionPerformed(evt);
            }
        });
        jToolBar2.add(BotonLinea);

        paint.add(BotonRectangulo);
        BotonRectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/rectangulo.png"))); // NOI18N
        BotonRectangulo.setBorderPainted(false);
        BotonRectangulo.setFocusable(false);
        BotonRectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonRectangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRectanguloActionPerformed(evt);
            }
        });
        jToolBar2.add(BotonRectangulo);

        paint.add(BotonElipse);
        BotonElipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/elipse.png"))); // NOI18N
        BotonElipse.setToolTipText("");
        BotonElipse.setBorderPainted(false);
        BotonElipse.setFocusable(false);
        BotonElipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonElipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonElipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonElipseActionPerformed(evt);
            }
        });
        jToolBar2.add(BotonElipse);

        paint.add(BotonFantasma);
        BotonFantasma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fantasma.png"))); // NOI18N
        BotonFantasma.setFocusable(false);
        BotonFantasma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonFantasma.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonFantasma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFantasmaActionPerformed(evt);
            }
        });
        jToolBar2.add(BotonFantasma);

        paint.add(BotonMover);
        BotonMover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/seleccion.png"))); // NOI18N
        BotonMover.setFocusable(false);
        BotonMover.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonMover.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonMover.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BotonMoverStateChanged(evt);
            }
        });
        BotonMover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMoverActionPerformed(evt);
            }
        });
        jToolBar2.add(BotonMover);
        jToolBar2.add(jSeparator1);

        BotonColor.setBackground(new java.awt.Color(0, 0, 0));
        BotonColor.setActionCommand("color");
        BotonColor.setFocusable(false);
        BotonColor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonColor.setOpaque(true);
        BotonColor.setPreferredSize(new java.awt.Dimension(34, 32));
        BotonColor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonColorActionPerformed(evt);
            }
        });
        jToolBar2.add(BotonColor);

        BotonRelleno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/rellenar.png"))); // NOI18N
        BotonRelleno.setFocusable(false);
        BotonRelleno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonRelleno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonRelleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRellenoActionPerformed(evt);
            }
        });
        jToolBar2.add(BotonRelleno);

        BotonTransparencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/transparencia.png"))); // NOI18N
        BotonTransparencia.setFocusable(false);
        BotonTransparencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonTransparencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonTransparencia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BotonTransparenciaStateChanged(evt);
            }
        });
        BotonTransparencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTransparenciaActionPerformed(evt);
            }
        });
        jToolBar2.add(BotonTransparencia);

        BotonAlisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/alisar.png"))); // NOI18N
        BotonAlisar.setFocusable(false);
        BotonAlisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonAlisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonAlisar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BotonAlisarStateChanged(evt);
            }
        });
        BotonAlisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAlisarActionPerformed(evt);
            }
        });
        jToolBar2.add(BotonAlisar);

        Grosor.setValue(0);
        Grosor.setPreferredSize(new java.awt.Dimension(75, 20));
        Grosor.setRequestFocusEnabled(false);
        Grosor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                GrosorStateChanged(evt);
            }
        });
        jToolBar2.add(Grosor);
        jToolBar2.add(jSeparator2);

        Volcado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos2/volcado.png"))); // NOI18N
        Volcado.setFocusable(false);
        Volcado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Volcado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Volcado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolcadoActionPerformed(evt);
            }
        });
        jToolBar2.add(Volcado);

        PanelToolBar.add(jToolBar2);

        getContentPane().add(PanelToolBar, java.awt.BorderLayout.PAGE_START);

        PanelEstado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelEstado.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        LabelEstado.setText("Barra de estado");
        PanelEstado.add(LabelEstado);

        getContentPane().add(PanelEstado, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 941, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        getContentPane().add(escritorio, java.awt.BorderLayout.CENTER);

        jMenu2.setText("File");

        MenuNuevo.setText("Nuevo");
        MenuNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuNuevoActionPerformed(evt);
            }
        });
        jMenu2.add(MenuNuevo);

        MenuAbrir.setText("Abrir");
        MenuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAbrirActionPerformed(evt);
            }
        });
        jMenu2.add(MenuAbrir);

        MenuGuardar.setText("Guardar");
        MenuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGuardarActionPerformed(evt);
            }
        });
        jMenu2.add(MenuGuardar);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNuevoActionPerformed
        VentanaInterna vi = new VentanaInterna();
        escritorio.add(vi);
        vi.setVisible(true);
        BufferedImage img;
        img = new BufferedImage(500,500,BufferedImage.TYPE_INT_RGB);
        Graphics2D g2d = img.createGraphics();
        g2d.setColor(Color.WHITE);
        g2d.fillRect(0, 0, img.getWidth(), img.getHeight());
        g2d.dispose();
        vi.getLienzo2D().setImg(img);
    }//GEN-LAST:event_MenuNuevoActionPerformed

    private void MenuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGuardarActionPerformed
        VentanaInterna vi=(VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getPaintedImage();
            if (img != null) {
                JFileChooser dlg = new JFileChooser();
                int resp = dlg.showSaveDialog(this);
                if (resp == JFileChooser.APPROVE_OPTION) {
                    try {
                        File f = dlg.getSelectedFile();
                        ImageIO.write(img, "jpg", f);
                        vi.setTitle(f.getName());
                    } catch (Exception ex) {
                        System.err.println("Error al guardar la imagen");
                    }
                }
            }
        }
    }//GEN-LAST:event_MenuGuardarActionPerformed

    private void BotonLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLineaActionPerformed
        if(this.getSelectedLienzo() != null)    this.getSelectedLienzo().setHerramienta(Linea);
        LabelEstado.setText("Dibujando Linea");
    }//GEN-LAST:event_BotonLineaActionPerformed

    private void BotonRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRectanguloActionPerformed
        if(this.getSelectedLienzo() != null)    this.getSelectedLienzo().setHerramienta(Rectangulo);
        LabelEstado.setText("Dibujando Rectangulo");
    }//GEN-LAST:event_BotonRectanguloActionPerformed

    private void BotonElipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonElipseActionPerformed
        if(this.getSelectedLienzo() != null)    this.getSelectedLienzo().setHerramienta(Elipse);
        LabelEstado.setText("Dibujando Elipse");
    }//GEN-LAST:event_BotonElipseActionPerformed

    private void BotonFantasmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFantasmaActionPerformed
        if(this.getSelectedLienzo() != null)    this.getSelectedLienzo().setHerramienta(Fantasma);
        LabelEstado.setText("Dibujando Fantasma");
    }//GEN-LAST:event_BotonFantasmaActionPerformed

    private void BotonRellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRellenoActionPerformed
        if(this.getSelectedLienzo() != null){
            this.getSelectedLienzo().setRelleno(this.BotonRelleno.isSelected());
            this.getSelectedLienzo().actualizarSelectedFigure();
        } 
    }//GEN-LAST:event_BotonRellenoActionPerformed

    private void BotonColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonColorActionPerformed
        Color nuevoColor = JColorChooser.showDialog(null, "Elige un color", null);
        if (nuevoColor != null) {
            BotonColor.setBackground(nuevoColor);
            if(this.getSelectedLienzo() != null){
                this.getSelectedLienzo().setColor(nuevoColor);
                this.getSelectedLienzo().actualizarSelectedFigure();
            }
        }
    }//GEN-LAST:event_BotonColorActionPerformed

    private void BotonMoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMoverActionPerformed
        if(this.getSelectedLienzo() != null)    this.getSelectedLienzo().setHerramienta(Arrastrar);
        LabelEstado.setText("Arrastar selecionado");
        if(this.getSelectedLienzo() != null)    this.getSelectedLienzo().setMover(this.BotonMover.isSelected());
    }//GEN-LAST:event_BotonMoverActionPerformed

    private void GrosorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_GrosorStateChanged
        Stroke trazo = new BasicStroke(this.Grosor.getValue());
        if(this.getSelectedLienzo() != null){
            this.getSelectedLienzo().setTrazo(trazo);
            this.getSelectedLienzo().actualizarSelectedFigure();
        }        
    }//GEN-LAST:event_GrosorStateChanged

    private void BotonAlisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAlisarActionPerformed
        if(this.getSelectedLienzo() != null){
            this.getSelectedLienzo().setAlisado(this.BotonAlisar.isSelected());
            this.getSelectedLienzo().actualizarSelectedFigure();
        }        
    }//GEN-LAST:event_BotonAlisarActionPerformed

    private void BotonTransparenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTransparenciaActionPerformed
        if(this.getSelectedLienzo() != null){
            this.getSelectedLienzo().setTransparencia(this.BotonTransparencia.isSelected());
            this.getSelectedLienzo().actualizarSelectedFigure();
        }        
    }//GEN-LAST:event_BotonTransparenciaActionPerformed

    private void BotonMoverStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BotonMoverStateChanged
        if(this.getSelectedLienzo() != null)    this.getSelectedLienzo().setMover(this.BotonMover.isSelected());
    }//GEN-LAST:event_BotonMoverStateChanged

    private void BotonTransparenciaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BotonTransparenciaStateChanged
        if(this.getSelectedLienzo() != null)    this.getSelectedLienzo().setTransparencia(this.BotonTransparencia.isSelected());
    }//GEN-LAST:event_BotonTransparenciaStateChanged

    private void BotonAlisarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BotonAlisarStateChanged
        if(this.getSelectedLienzo() != null)    this.getSelectedLienzo().setAlisado(this.BotonAlisar.isSelected());
    }//GEN-LAST:event_BotonAlisarStateChanged

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        MenuNuevoActionPerformed(evt);
    }//GEN-LAST:event_NuevoActionPerformed

    private void AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirActionPerformed
        MenuAbrirActionPerformed(evt);
    }//GEN-LAST:event_AbrirActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        MenuGuardarActionPerformed(evt);
    }//GEN-LAST:event_GuardarActionPerformed

    private void VolcadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolcadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VolcadoActionPerformed

    private void MenuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAbrirActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if( resp == JFileChooser.APPROVE_OPTION) {
            try{
                File f = dlg.getSelectedFile();
                BufferedImage img = ImageIO.read(f);
                VentanaInterna vi = new VentanaInterna();
                vi.getLienzo2D().setImg(img);
                this.escritorio.add(vi);
                vi.setTitle(f.getName());
                vi.setVisible(true);
            }catch(Exception ex){
                System.err.println("Error al leer la imagen");
            }
        }
    }//GEN-LAST:event_MenuAbrirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Abrir;
    private javax.swing.JToggleButton BotonAlisar;
    private javax.swing.JButton BotonColor;
    private javax.swing.JToggleButton BotonElipse;
    private javax.swing.JToggleButton BotonFantasma;
    private javax.swing.JToggleButton BotonLinea;
    private javax.swing.JToggleButton BotonMover;
    private javax.swing.JToggleButton BotonRectangulo;
    private javax.swing.JToggleButton BotonRelleno;
    private javax.swing.JToggleButton BotonTransparencia;
    private javax.swing.JSlider Grosor;
    private javax.swing.JButton Guardar;
    private javax.swing.JLabel LabelEstado;
    private javax.swing.JMenuItem MenuAbrir;
    private javax.swing.JMenuItem MenuGuardar;
    private javax.swing.JMenuItem MenuNuevo;
    private javax.swing.JButton Nuevo;
    private javax.swing.JPanel PanelEstado;
    private javax.swing.JPanel PanelToolBar;
    private javax.swing.JButton Volcado;
    private javax.swing.ButtonGroup colo;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.ButtonGroup paint;
    // End of variables declaration//GEN-END:variables
}
