package p11;


import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.SwingUtilities;
import sm.dsv.Imagen.PanelLienzo;

/**
 *
 * @author Diego
 */
public class VentanaInterna extends javax.swing.JInternalFrame {

    //private PanelLienzo lienzo;
    private static int xOffset = 20;
    private static int yOffset = 20;

    /**
     * Creates new form VentanaInterna
     */
    public VentanaInterna() {
        super("Nueva Ventana",
              true,   // resizable
              true,   // closable
              true,   // maximizable
              true);  // iconifiable
        
        initComponents();

        // Establece el tamaño predeterminado de la ventana interna
        this.setSize(600, 600);
    }
    
    public VentanaInterna(JDesktopPane escritorio){
        this();
        posicionVentana(escritorio);      
    }
    
    public VentanaInterna(VentanaInterna otra){
        this();
        this.setTitle(otra.getTitle() + " (Copia)");
        
        // Clona el lienzo de la ventana interna original y configura el lienzo de la nueva ventana interna
        PanelLienzo lienzoOriginal = otra.getLienzo2D();
        PanelLienzo lienzoNuevo = new PanelLienzo();
        lienzoNuevo.setImg(lienzoOriginal.getImg()); // Clona la imagen del lienzo original
        this.lienzo = lienzoNuevo;

        // Agrega el nuevo lienzo al panel de la nueva ventana interna
        jScrollPane1.setViewportView(lienzoNuevo);

        // Establece el tamaño predeterminado de la ventana interna
        this.setSize(otra.getWidth(), otra.getHeight());     
        JDesktopPane escritorio = findDesktopPane(otra);
        if (escritorio != null) {
            posicionVentana(escritorio);
        }
    }

    
    // Método para obtener el lienzo 2D
    public PanelLienzo getLienzo2D() {
        return lienzo;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lienzo = new sm.dsv.Imagen.PanelLienzo();

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(lienzo);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private sm.dsv.Imagen.PanelLienzo lienzo;
    // End of variables declaration//GEN-END:variables

    private void posicionVentana(JDesktopPane escritorio) {
        JInternalFrame[] allFrames = escritorio.getAllFrames();
        int x = 0, y = 0;
        
        if(allFrames.length > 0){
            JInternalFrame ultimoFrame = allFrames[0];
            x = ultimoFrame.getX() + xOffset;
            y = ultimoFrame.getY() + yOffset;
        }
        
        if(x + this.getWidth() > escritorio.getWidth()){
            x = 0;
        }
        
        if( y + this.getHeight() > escritorio.getHeight()){
            y = 0;
        }
        
        this.setLocation(x, y);
        //System.out.println("p11.VentanaInterna.posicionVentana()  " + allFrames.length );
    }
    
    
    private JDesktopPane findDesktopPane(javax.swing.JInternalFrame frame) {
        // Get the parent of the frame
        javax.swing.JComponent parent = (javax.swing.JComponent) SwingUtilities.getAncestorOfClass(javax.swing.JDesktopPane.class, frame);
        // Check if the parent is a JDesktopPane
        if (parent instanceof javax.swing.JDesktopPane) {
            return (javax.swing.JDesktopPane) parent;
        }
        // If not found, return null
        return null;
    }
}
