/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package p4;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.Shape;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;
import java.awt.geom.Point2D;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Diego
 */
public class PanelLienzo extends javax.swing.JPanel {

    enum Herramienta{
        Linea, Rectangulo, Elipse
    }
    
    private Shape forma = new Line2D.Float();
    private Color color = Color.black;
    private Boolean relleno = false;
    private Boolean mover = false;
    private Herramienta herramienta;
    private Point punto;
    
    private List<Shape> vShape = new ArrayList();

    public Shape getForma() {
        return forma;
    }

    public void setForma(Shape forma) {
        this.forma = forma;
    }

    public Color getColor() {
        return color;
    }

    public void setColor(Color color) {
        this.color = color;
    }

    public Boolean getRelleno() {
        return relleno;
    }

    public void setRelleno(Boolean relleno) {
        this.relleno = relleno;
    }
    
    public Boolean getMover() {
        return mover;
    }

    public void setMover(Boolean mover) {
        this.mover = mover;
    }

    public Herramienta getHerramienta() {
        return herramienta;
    }

    public void setHerramienta(Herramienta herramienta) {
        this.herramienta = herramienta;
    }
    
    
    /**
     * Creates new form PanelLienzo
     */
    public PanelLienzo() {
        initComponents();
    }

    @Override
    public void paint(Graphics g){
        super.paint(g);
        Graphics2D g2d = (Graphics2D)g;
        
        
        g2d.setPaint(color);
        /*
        if(relleno){
            g2d.fill(forma);
        }
        */
        //g2d.draw(forma);
        for(Shape s:vShape){
            if(relleno){
                g2d.fill(s);
            }
            g2d.draw(s);
        }
    }
    
    private Shape figuraSeleccionada(Point2D p){
        for(Shape s:vShape)
            if(s.contains(p)) return s;
        return null;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        punto = evt.getPoint();
        if(mover){
            forma = figuraSeleccionada(punto);
        }else{
             switch (herramienta) {
                case Linea: 
                    forma = new Line2D.Float(evt.getPoint(),evt.getPoint());
                    break;
                case Rectangulo:
                    forma = new Rectangle2D.Float(evt.getPoint().x,evt.getPoint().y,evt.getPoint().x,evt.getPoint().y);
                    break;

                case Elipse:
                    forma = new Ellipse2D.Float(evt.getPoint().x,evt.getPoint().y,evt.getPoint().x,evt.getPoint().y);
                    break;
                default:
                    throw new AssertionError();
            }           
        }
        vShape.add(forma); 
    
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        if(mover){
            /*
            if(forma!=null && forma instanceof Rectangle){
                ((Line2D)forma).setLocation(evt.getPoint());
            }
            */
            if(forma!=null && forma instanceof Rectangle){
                ((Rectangle)forma).setLocation(evt.getPoint());
            }
            /*
            if(forma!=null && forma instanceof Rectangle){
                ((Ellipse2D)forma).setLocation(evt.getPoint());
            }
            */
        }else{
            if(herramienta == Herramienta.Linea){
                ((Line2D)forma).setLine(((Line2D)forma).getP1(), evt.getPoint());
            }
            if(herramienta == Herramienta.Rectangulo){
                ((Rectangle2D)forma).setFrameFromDiagonal(punto,evt.getPoint());
            }
            if(herramienta == Herramienta.Elipse){
                ((Ellipse2D)forma).setFrameFromDiagonal(punto, evt.getPoint());
            }


        this.repaint();
    }//GEN-LAST:event_formMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    }
}
