/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package p4;

import java.awt.Color;
import static p4.PanelLienzo.Herramienta.Elipse;
import static p4.PanelLienzo.Herramienta.Linea;
import static p4.PanelLienzo.Herramienta.Rectangulo;

/**
 *
 * @author Diego
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paint = new javax.swing.ButtonGroup();
        colo = new javax.swing.ButtonGroup();
        moverRelleno = new javax.swing.ButtonGroup();
        PanelToolBar = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        BotonLinea = new javax.swing.JToggleButton();
        BotonRectangulo = new javax.swing.JToggleButton();
        BotonElipse = new javax.swing.JToggleButton();
        panelLienzo1 = new p4.PanelLienzo();
        PanelDeAbajo = new javax.swing.JPanel();
        Colores = new javax.swing.JPanel();
        BlackButton = new javax.swing.JToggleButton();
        RedButton = new javax.swing.JToggleButton();
        BlueButton = new javax.swing.JToggleButton();
        WhiteButton = new javax.swing.JToggleButton();
        YellowButton = new javax.swing.JToggleButton();
        GreenButton = new javax.swing.JToggleButton();
        PanelRelleno = new javax.swing.JPanel();
        Mover = new javax.swing.JCheckBox();
        Relleno = new javax.swing.JCheckBox();
        PanelEstado = new javax.swing.JPanel();
        LabelEstado = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelToolBar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jToolBar2.setRollover(true);
        jToolBar2.setBorderPainted(false);

        paint.add(BotonLinea);
        BotonLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p4/linea.png"))); // NOI18N
        BotonLinea.setBorderPainted(false);
        BotonLinea.setFocusable(false);
        BotonLinea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonLinea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLineaActionPerformed(evt);
            }
        });
        jToolBar2.add(BotonLinea);

        paint.add(BotonRectangulo);
        BotonRectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p4/rectangulo.png"))); // NOI18N
        BotonRectangulo.setBorderPainted(false);
        BotonRectangulo.setFocusable(false);
        BotonRectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonRectangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRectanguloActionPerformed(evt);
            }
        });
        jToolBar2.add(BotonRectangulo);

        paint.add(BotonElipse);
        BotonElipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p4/elipse.png"))); // NOI18N
        BotonElipse.setToolTipText("");
        BotonElipse.setBorderPainted(false);
        BotonElipse.setFocusable(false);
        BotonElipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonElipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonElipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonElipseActionPerformed(evt);
            }
        });
        jToolBar2.add(BotonElipse);

        PanelToolBar.add(jToolBar2);

        getContentPane().add(PanelToolBar, java.awt.BorderLayout.PAGE_START);

        panelLienzo1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelLienzo1Layout = new javax.swing.GroupLayout(panelLienzo1);
        panelLienzo1.setLayout(panelLienzo1Layout);
        panelLienzo1Layout.setHorizontalGroup(
            panelLienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 941, Short.MAX_VALUE)
        );
        panelLienzo1Layout.setVerticalGroup(
            panelLienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );

        getContentPane().add(panelLienzo1, java.awt.BorderLayout.CENTER);

        PanelDeAbajo.setMaximumSize(new java.awt.Dimension(180, 120));
        PanelDeAbajo.setPreferredSize(new java.awt.Dimension(70, 69));
        PanelDeAbajo.setLayout(new java.awt.BorderLayout());

        Colores.setMaximumSize(new java.awt.Dimension(90, 60));
        Colores.setPreferredSize(new java.awt.Dimension(90, 60));
        Colores.setLayout(new java.awt.GridLayout(2, 0));

        BlackButton.setBackground(new java.awt.Color(0, 0, 0));
        colo.add(BlackButton);
        BlackButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BlackButton.setMaximumSize(new java.awt.Dimension(30, 30));
        BlackButton.setMinimumSize(new java.awt.Dimension(30, 30));
        BlackButton.setPreferredSize(new java.awt.Dimension(30, 30));
        BlackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlackButtonActionPerformed(evt);
            }
        });
        Colores.add(BlackButton);

        RedButton.setBackground(new java.awt.Color(255, 0, 0));
        colo.add(RedButton);
        RedButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RedButton.setMaximumSize(new java.awt.Dimension(30, 30));
        RedButton.setMinimumSize(new java.awt.Dimension(30, 30));
        RedButton.setPreferredSize(new java.awt.Dimension(30, 30));
        RedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RedButtonActionPerformed(evt);
            }
        });
        Colores.add(RedButton);

        BlueButton.setBackground(new java.awt.Color(0, 0, 255));
        colo.add(BlueButton);
        BlueButton.setSelected(true);
        BlueButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BlueButton.setMaximumSize(new java.awt.Dimension(30, 30));
        BlueButton.setMinimumSize(new java.awt.Dimension(30, 30));
        BlueButton.setPreferredSize(new java.awt.Dimension(30, 30));
        BlueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlueButtonActionPerformed(evt);
            }
        });
        Colores.add(BlueButton);

        colo.add(WhiteButton);
        WhiteButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        WhiteButton.setMaximumSize(new java.awt.Dimension(30, 30));
        WhiteButton.setMinimumSize(new java.awt.Dimension(30, 30));
        WhiteButton.setPreferredSize(new java.awt.Dimension(30, 30));
        WhiteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WhiteButtonActionPerformed(evt);
            }
        });
        Colores.add(WhiteButton);

        YellowButton.setBackground(new java.awt.Color(255, 255, 0));
        colo.add(YellowButton);
        YellowButton.setForeground(new java.awt.Color(255, 255, 0));
        YellowButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        YellowButton.setMaximumSize(new java.awt.Dimension(30, 30));
        YellowButton.setMinimumSize(new java.awt.Dimension(30, 30));
        YellowButton.setPreferredSize(new java.awt.Dimension(30, 30));
        YellowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YellowButtonActionPerformed(evt);
            }
        });
        Colores.add(YellowButton);

        GreenButton.setBackground(new java.awt.Color(0, 255, 0));
        colo.add(GreenButton);
        GreenButton.setToolTipText("");
        GreenButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        GreenButton.setMaximumSize(new java.awt.Dimension(30, 30));
        GreenButton.setMinimumSize(new java.awt.Dimension(30, 30));
        GreenButton.setPreferredSize(new java.awt.Dimension(30, 30));
        GreenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GreenButtonActionPerformed(evt);
            }
        });
        Colores.add(GreenButton);

        PanelDeAbajo.add(Colores, java.awt.BorderLayout.WEST);

        PanelRelleno.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        moverRelleno.add(Mover);
        Mover.setText("Mover");
        Mover.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                MoverStateChanged(evt);
            }
        });
        Mover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoverActionPerformed(evt);
            }
        });
        PanelRelleno.add(Mover);

        moverRelleno.add(Relleno);
        Relleno.setText("Relleno");
        Relleno.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RellenoStateChanged(evt);
            }
        });
        Relleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RellenoActionPerformed(evt);
            }
        });
        PanelRelleno.add(Relleno);

        PanelDeAbajo.add(PanelRelleno, java.awt.BorderLayout.EAST);

        PanelEstado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelEstado.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        LabelEstado.setText("Barra de estado");
        PanelEstado.add(LabelEstado);

        PanelDeAbajo.add(PanelEstado, java.awt.BorderLayout.SOUTH);

        getContentPane().add(PanelDeAbajo, java.awt.BorderLayout.PAGE_END);

        jMenu2.setText("File");

        jMenuItem1.setText("Nuevo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Abrir");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Guardar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void RedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedButtonActionPerformed
        panelLienzo1.setColor(Color.red);
    }//GEN-LAST:event_RedButtonActionPerformed

    private void BlackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlackButtonActionPerformed
        panelLienzo1.setColor(Color.black);
    }//GEN-LAST:event_BlackButtonActionPerformed

    private void BlueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlueButtonActionPerformed
        panelLienzo1.setColor(Color.blue);
    }//GEN-LAST:event_BlueButtonActionPerformed

    private void WhiteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WhiteButtonActionPerformed
        panelLienzo1.setColor(Color.white);
    }//GEN-LAST:event_WhiteButtonActionPerformed

    private void YellowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YellowButtonActionPerformed
        panelLienzo1.setColor(Color.yellow);
    }//GEN-LAST:event_YellowButtonActionPerformed

    private void GreenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GreenButtonActionPerformed
        panelLienzo1.setColor(Color.green);
    }//GEN-LAST:event_GreenButtonActionPerformed

    private void RellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RellenoActionPerformed
    }//GEN-LAST:event_RellenoActionPerformed

    private void BotonLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLineaActionPerformed
        panelLienzo1.setHerramienta(Linea);
        LabelEstado.setText("Dibujando Linea");
    }//GEN-LAST:event_BotonLineaActionPerformed

    private void BotonRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRectanguloActionPerformed
        panelLienzo1.setHerramienta(Rectangulo);
        LabelEstado.setText("Dibujando Rectangulo");
    }//GEN-LAST:event_BotonRectanguloActionPerformed

    private void BotonElipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonElipseActionPerformed
        panelLienzo1.setHerramienta(Elipse);
        LabelEstado.setText("Dibujando Elipse");
    }//GEN-LAST:event_BotonElipseActionPerformed

    private void RellenoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RellenoStateChanged
        panelLienzo1.setRelleno(this.Relleno.isSelected());
    }//GEN-LAST:event_RellenoStateChanged

    private void MoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MoverActionPerformed

    private void MoverStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_MoverStateChanged
        panelLienzo1.setMover(this.Mover.isSelected());
    }//GEN-LAST:event_MoverStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BlackButton;
    private javax.swing.JToggleButton BlueButton;
    private javax.swing.JToggleButton BotonElipse;
    private javax.swing.JToggleButton BotonLinea;
    private javax.swing.JToggleButton BotonRectangulo;
    private javax.swing.JPanel Colores;
    private javax.swing.JToggleButton GreenButton;
    private javax.swing.JLabel LabelEstado;
    private javax.swing.JCheckBox Mover;
    private javax.swing.JPanel PanelDeAbajo;
    private javax.swing.JPanel PanelEstado;
    private javax.swing.JPanel PanelRelleno;
    private javax.swing.JPanel PanelToolBar;
    private javax.swing.JToggleButton RedButton;
    private javax.swing.JCheckBox Relleno;
    private javax.swing.JToggleButton WhiteButton;
    private javax.swing.JToggleButton YellowButton;
    private javax.swing.ButtonGroup colo;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.ButtonGroup moverRelleno;
    private javax.swing.ButtonGroup paint;
    private p4.PanelLienzo panelLienzo1;
    // End of variables declaration//GEN-END:variables
}
