
package p7;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Stroke;
import javax.swing.JColorChooser;
import static sm.dsv.graficos.PanelLienzo.Herramienta.Elipse;
import static sm.dsv.graficos.PanelLienzo.Herramienta.Fantasma;
import static sm.dsv.graficos.PanelLienzo.Herramienta.Linea;
import static sm.dsv.graficos.PanelLienzo.Herramienta.Rectangulo;
import static sm.dsv.graficos.PanelLienzo.Herramienta.Arrastrar;


/**
 *
 * @author Diego
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paint = new javax.swing.ButtonGroup();
        colo = new javax.swing.ButtonGroup();
        jColorChooser1 = new javax.swing.JColorChooser();
        PanelToolBar = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        BotonLinea = new javax.swing.JToggleButton();
        BotonRectangulo = new javax.swing.JToggleButton();
        BotonElipse = new javax.swing.JToggleButton();
        BotonFantasma = new javax.swing.JToggleButton();
        BotonMover = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        BotonColor = new javax.swing.JButton();
        BotonRelleno = new javax.swing.JToggleButton();
        BotonTransparencia = new javax.swing.JToggleButton();
        BotonAlisar = new javax.swing.JToggleButton();
        Grosor = new javax.swing.JSlider();
        PanelEstado = new javax.swing.JPanel();
        LabelEstado = new javax.swing.JLabel();
        panelLienzo1 = new sm.dsv.graficos.PanelLienzo();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelToolBar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jToolBar2.setRollover(true);
        jToolBar2.setBorderPainted(false);

        paint.add(BotonLinea);
        BotonLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p7/iconos/linea.png"))); // NOI18N
        BotonLinea.setBorderPainted(false);
        BotonLinea.setFocusable(false);
        BotonLinea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonLinea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLineaActionPerformed(evt);
            }
        });
        jToolBar2.add(BotonLinea);

        paint.add(BotonRectangulo);
        BotonRectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p7/iconos/rectangulo.png"))); // NOI18N
        BotonRectangulo.setBorderPainted(false);
        BotonRectangulo.setFocusable(false);
        BotonRectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonRectangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRectanguloActionPerformed(evt);
            }
        });
        jToolBar2.add(BotonRectangulo);

        paint.add(BotonElipse);
        BotonElipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p7/iconos/elipse.png"))); // NOI18N
        BotonElipse.setToolTipText("");
        BotonElipse.setBorderPainted(false);
        BotonElipse.setFocusable(false);
        BotonElipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonElipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonElipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonElipseActionPerformed(evt);
            }
        });
        jToolBar2.add(BotonElipse);

        paint.add(BotonFantasma);
        BotonFantasma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p7/iconos/fantasma.png"))); // NOI18N
        BotonFantasma.setFocusable(false);
        BotonFantasma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonFantasma.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonFantasma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFantasmaActionPerformed(evt);
            }
        });
        jToolBar2.add(BotonFantasma);

        paint.add(BotonMover);
        BotonMover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p7/iconos/seleccion.png"))); // NOI18N
        BotonMover.setFocusable(false);
        BotonMover.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonMover.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonMover.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BotonMoverStateChanged(evt);
            }
        });
        BotonMover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMoverActionPerformed(evt);
            }
        });
        jToolBar2.add(BotonMover);
        jToolBar2.add(jSeparator1);

        BotonColor.setBackground(new java.awt.Color(0, 0, 0));
        BotonColor.setActionCommand("color");
        BotonColor.setFocusable(false);
        BotonColor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonColor.setOpaque(true);
        BotonColor.setPreferredSize(new java.awt.Dimension(34, 32));
        BotonColor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonColorActionPerformed(evt);
            }
        });
        jToolBar2.add(BotonColor);

        BotonRelleno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p7/iconos/rellenar.png"))); // NOI18N
        BotonRelleno.setFocusable(false);
        BotonRelleno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonRelleno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonRelleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRellenoActionPerformed(evt);
            }
        });
        jToolBar2.add(BotonRelleno);

        BotonTransparencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p7/iconos/transparencia.png"))); // NOI18N
        BotonTransparencia.setFocusable(false);
        BotonTransparencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonTransparencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonTransparencia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BotonTransparenciaStateChanged(evt);
            }
        });
        BotonTransparencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTransparenciaActionPerformed(evt);
            }
        });
        jToolBar2.add(BotonTransparencia);

        BotonAlisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p7/iconos/alisar.png"))); // NOI18N
        BotonAlisar.setFocusable(false);
        BotonAlisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonAlisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonAlisar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BotonAlisarStateChanged(evt);
            }
        });
        BotonAlisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAlisarActionPerformed(evt);
            }
        });
        jToolBar2.add(BotonAlisar);

        Grosor.setValue(0);
        Grosor.setPreferredSize(new java.awt.Dimension(75, 20));
        Grosor.setRequestFocusEnabled(false);
        Grosor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                GrosorStateChanged(evt);
            }
        });
        jToolBar2.add(Grosor);

        PanelToolBar.add(jToolBar2);

        getContentPane().add(PanelToolBar, java.awt.BorderLayout.PAGE_START);

        PanelEstado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelEstado.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        LabelEstado.setText("Barra de estado");
        PanelEstado.add(LabelEstado);

        getContentPane().add(PanelEstado, java.awt.BorderLayout.SOUTH);

        panelLienzo1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelLienzo1Layout = new javax.swing.GroupLayout(panelLienzo1);
        panelLienzo1.setLayout(panelLienzo1Layout);
        panelLienzo1Layout.setHorizontalGroup(
            panelLienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 941, Short.MAX_VALUE)
        );
        panelLienzo1Layout.setVerticalGroup(
            panelLienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        getContentPane().add(panelLienzo1, java.awt.BorderLayout.CENTER);

        jMenu2.setText("File");

        jMenuItem1.setText("Nuevo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Abrir");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Guardar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void BotonLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLineaActionPerformed
        panelLienzo1.setHerramienta(Linea);
        LabelEstado.setText("Dibujando Linea");
    }//GEN-LAST:event_BotonLineaActionPerformed

    private void BotonRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRectanguloActionPerformed
        panelLienzo1.setHerramienta(Rectangulo);
        LabelEstado.setText("Dibujando Rectangulo");
    }//GEN-LAST:event_BotonRectanguloActionPerformed

    private void BotonElipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonElipseActionPerformed
        panelLienzo1.setHerramienta(Elipse);
        LabelEstado.setText("Dibujando Elipse");
    }//GEN-LAST:event_BotonElipseActionPerformed

    private void BotonFantasmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFantasmaActionPerformed
        panelLienzo1.setHerramienta(Fantasma);
        LabelEstado.setText("Dibujando Fantasma");
    }//GEN-LAST:event_BotonFantasmaActionPerformed

    private void BotonRellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRellenoActionPerformed
        panelLienzo1.setRelleno(this.BotonRelleno.isSelected());
    }//GEN-LAST:event_BotonRellenoActionPerformed

    private void BotonColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonColorActionPerformed
        Color nuevoColor = JColorChooser.showDialog(null, "Elige un color", null);
        if (nuevoColor != null) {
            BotonColor.setBackground(nuevoColor);
            panelLienzo1.setColor(nuevoColor);
        }
    }//GEN-LAST:event_BotonColorActionPerformed

    private void BotonMoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMoverActionPerformed
        panelLienzo1.setHerramienta(Arrastrar);
        LabelEstado.setText("Arrastar selecionado");
        panelLienzo1.setMover(this.BotonMover.isSelected());
    }//GEN-LAST:event_BotonMoverActionPerformed

    private void GrosorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_GrosorStateChanged
        Stroke trazo = new BasicStroke(this.Grosor.getValue());
        panelLienzo1.setTrazo(trazo);
    }//GEN-LAST:event_GrosorStateChanged

    private void BotonAlisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAlisarActionPerformed
        panelLienzo1.setAlisado(this.BotonAlisar.isSelected());
    }//GEN-LAST:event_BotonAlisarActionPerformed

    private void BotonTransparenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTransparenciaActionPerformed
        panelLienzo1.setTransparencia(this.BotonTransparencia.isSelected());
    }//GEN-LAST:event_BotonTransparenciaActionPerformed

    private void BotonMoverStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BotonMoverStateChanged
        panelLienzo1.setMover(this.BotonMover.isSelected());
    }//GEN-LAST:event_BotonMoverStateChanged

    private void BotonTransparenciaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BotonTransparenciaStateChanged
        panelLienzo1.setTransparencia(this.BotonTransparencia.isSelected());
    }//GEN-LAST:event_BotonTransparenciaStateChanged

    private void BotonAlisarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BotonAlisarStateChanged
        panelLienzo1.setAlisado(this.BotonAlisar.isSelected());
    }//GEN-LAST:event_BotonAlisarStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotonAlisar;
    private javax.swing.JButton BotonColor;
    private javax.swing.JToggleButton BotonElipse;
    private javax.swing.JToggleButton BotonFantasma;
    private javax.swing.JToggleButton BotonLinea;
    private javax.swing.JToggleButton BotonMover;
    private javax.swing.JToggleButton BotonRectangulo;
    private javax.swing.JToggleButton BotonRelleno;
    private javax.swing.JToggleButton BotonTransparencia;
    private javax.swing.JSlider Grosor;
    private javax.swing.JLabel LabelEstado;
    private javax.swing.JPanel PanelEstado;
    private javax.swing.JPanel PanelToolBar;
    private javax.swing.ButtonGroup colo;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.ButtonGroup paint;
    private sm.dsv.graficos.PanelLienzo panelLienzo1;
    // End of variables declaration//GEN-END:variables
}
