
package p13;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.Stroke;
import java.awt.Transparency;
import java.awt.color.ColorSpace;
import java.awt.geom.AffineTransform;
import java.awt.image.AffineTransformOp;
import java.awt.image.BandCombineOp;
import java.awt.image.BufferedImage;
import java.awt.image.ByteLookupTable;
import java.awt.image.ColorConvertOp;
import java.awt.image.ColorModel;
import java.awt.image.ComponentColorModel;
import java.awt.image.ConvolveOp;
import java.awt.image.DataBuffer;
import java.awt.image.Kernel;
import java.awt.image.LookupOp;
import java.awt.image.LookupTable;
import java.awt.image.RescaleOp;
import java.awt.image.WritableRaster;
import java.io.File;
import javax.imageio.ImageIO;
import javax.sound.sampled.LineEvent;
import javax.sound.sampled.LineListener;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import sm.dsv.Imagen.PanelLienzo;
import static sm.dsv.Imagen.PanelLienzo.Herramienta.Elipse;
import static sm.dsv.Imagen.PanelLienzo.Herramienta.Fantasma;
import static sm.dsv.Imagen.PanelLienzo.Herramienta.Linea;
import static sm.dsv.Imagen.PanelLienzo.Herramienta.Rectangulo;
import static sm.dsv.Imagen.PanelLienzo.Herramienta.Arrastrar;
import sm.dsv.Imagen.PosterizarOP;
import sm.dsv.Imagen.RetoOp;
import sm.dsv.Imagen.RojoOp;
import sm.image.EqualizationOp;
import sm.image.KernelProducer;
import sm.image.LookupTableProducer;
import sm.image.SepiaOp;
import sm.image.TintOp;
import sm.sound.SMClipPlayer;
import sm.sound.SMSoundRecorder;


/**
 *
 * @author Diego
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private BufferedImage imgFuente;
    private SMClipPlayer player = null;
    private SMSoundRecorder recorder = null;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    private PanelLienzo getSelectedLienzo() {
        VentanaInterna vi;
        vi = (VentanaInterna)escritorio.getSelectedFrame();
        return vi!=null ? vi.getLienzo2D() : null;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paint = new javax.swing.ButtonGroup();
        colo = new javax.swing.ButtonGroup();
        jColorChooser1 = new javax.swing.JColorChooser();
        SonidoButtongroup = new javax.swing.ButtonGroup();
        PanelToolBar = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        Nuevo = new javax.swing.JButton();
        Abrir = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        CopiarYdesplazarVentana = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        BotonLinea = new javax.swing.JToggleButton();
        BotonRectangulo = new javax.swing.JToggleButton();
        BotonElipse = new javax.swing.JToggleButton();
        BotonFantasma = new javax.swing.JToggleButton();
        BotonMover = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        BotonColor = new javax.swing.JButton();
        BotonRelleno = new javax.swing.JToggleButton();
        BotonTransparencia = new javax.swing.JToggleButton();
        BotonAlisar = new javax.swing.JToggleButton();
        Grosor = new javax.swing.JSlider();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        Volcado = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        PlayButton = new javax.swing.JButton();
        StopButton = new javax.swing.JButton();
        AudioList = new javax.swing.JComboBox<>();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        GrabarButton = new javax.swing.JButton();
        escritorio = new javax.swing.JDesktopPane();
        PanelAbajo = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        BrilloSlider = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        ContrasteSlider = new javax.swing.JSlider();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        Mascara = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        CometaSlider = new javax.swing.JSlider();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        ContrasteButton = new javax.swing.JButton();
        OscurecerButton = new javax.swing.JButton();
        IluminarButton = new javax.swing.JButton();
        negativoButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        rotateSlider = new javax.swing.JSlider();
        TLinealSlider = new javax.swing.JSlider();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        Rotar180Button = new javax.swing.JButton();
        MasButton = new javax.swing.JButton();
        menosButton = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        ShowBandasButton = new javax.swing.JButton();
        seleccionEspacioCOLOR = new javax.swing.JComboBox<>();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        CombinarBandasButton = new javax.swing.JButton();
        tintarButton = new javax.swing.JButton();
        sepiaButton = new javax.swing.JButton();
        ecualizarButton = new javax.swing.JButton();
        rojoButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        posterizarSlider = new javax.swing.JSlider();
        ColorReto1Button = new javax.swing.JButton();
        retoFinalslider = new javax.swing.JSlider();
        ColorReto2Button = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        PanelEstado = new javax.swing.JPanel();
        LabelEstado = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        MenuNuevo = new javax.swing.JMenuItem();
        MenuAbrir = new javax.swing.JMenuItem();
        MenuGuardar = new javax.swing.JMenuItem();
        MenuAbrirAudio = new javax.swing.JMenuItem();
        menuImagen = new javax.swing.JMenu();
        RescaleOpMENU = new javax.swing.JMenuItem();
        ConvolveOpMENU = new javax.swing.JMenuItem();
        AffineTransformOpMENU = new javax.swing.JMenuItem();
        LookupOpMENU = new javax.swing.JMenuItem();
        reto1 = new javax.swing.JMenuItem();
        reto2 = new javax.swing.JMenuItem();
        BandCombineOpMENU = new javax.swing.JMenuItem();
        ColorConvertOpMENU = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelToolBar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jToolBar2.setRollover(true);
        jToolBar2.setBorderPainted(false);

        Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos2/nuevo.png"))); // NOI18N
        Nuevo.setFocusable(false);
        Nuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Nuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });
        jToolBar2.add(Nuevo);

        Abrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos2/abrir.png"))); // NOI18N
        Abrir.setFocusable(false);
        Abrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Abrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirActionPerformed(evt);
            }
        });
        jToolBar2.add(Abrir);

        Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos2/guardar.png"))); // NOI18N
        Guardar.setFocusable(false);
        Guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jToolBar2.add(Guardar);

        CopiarYdesplazarVentana.setText(".2x");
        CopiarYdesplazarVentana.setFocusable(false);
        CopiarYdesplazarVentana.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CopiarYdesplazarVentana.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CopiarYdesplazarVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CopiarYdesplazarVentanaActionPerformed(evt);
            }
        });
        jToolBar2.add(CopiarYdesplazarVentana);
        jToolBar2.add(jSeparator3);

        paint.add(BotonLinea);
        BotonLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/linea.png"))); // NOI18N
        BotonLinea.setBorderPainted(false);
        BotonLinea.setFocusable(false);
        BotonLinea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonLinea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLineaActionPerformed(evt);
            }
        });
        jToolBar2.add(BotonLinea);

        paint.add(BotonRectangulo);
        BotonRectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/rectangulo.png"))); // NOI18N
        BotonRectangulo.setBorderPainted(false);
        BotonRectangulo.setFocusable(false);
        BotonRectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonRectangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRectanguloActionPerformed(evt);
            }
        });
        jToolBar2.add(BotonRectangulo);

        paint.add(BotonElipse);
        BotonElipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/elipse.png"))); // NOI18N
        BotonElipse.setToolTipText("");
        BotonElipse.setBorderPainted(false);
        BotonElipse.setFocusable(false);
        BotonElipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonElipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonElipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonElipseActionPerformed(evt);
            }
        });
        jToolBar2.add(BotonElipse);

        paint.add(BotonFantasma);
        BotonFantasma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fantasma.png"))); // NOI18N
        BotonFantasma.setFocusable(false);
        BotonFantasma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonFantasma.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonFantasma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFantasmaActionPerformed(evt);
            }
        });
        jToolBar2.add(BotonFantasma);

        paint.add(BotonMover);
        BotonMover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/seleccion.png"))); // NOI18N
        BotonMover.setFocusable(false);
        BotonMover.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonMover.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonMover.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BotonMoverStateChanged(evt);
            }
        });
        BotonMover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMoverActionPerformed(evt);
            }
        });
        jToolBar2.add(BotonMover);
        jToolBar2.add(jSeparator1);

        BotonColor.setBackground(new java.awt.Color(0, 0, 0));
        BotonColor.setActionCommand("color");
        BotonColor.setFocusable(false);
        BotonColor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonColor.setOpaque(true);
        BotonColor.setPreferredSize(new java.awt.Dimension(34, 32));
        BotonColor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonColorActionPerformed(evt);
            }
        });
        jToolBar2.add(BotonColor);

        BotonRelleno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/rellenar.png"))); // NOI18N
        BotonRelleno.setFocusable(false);
        BotonRelleno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonRelleno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonRelleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRellenoActionPerformed(evt);
            }
        });
        jToolBar2.add(BotonRelleno);

        BotonTransparencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/transparencia.png"))); // NOI18N
        BotonTransparencia.setFocusable(false);
        BotonTransparencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonTransparencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonTransparencia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BotonTransparenciaStateChanged(evt);
            }
        });
        BotonTransparencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTransparenciaActionPerformed(evt);
            }
        });
        jToolBar2.add(BotonTransparencia);

        BotonAlisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/alisar.png"))); // NOI18N
        BotonAlisar.setFocusable(false);
        BotonAlisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonAlisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonAlisar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BotonAlisarStateChanged(evt);
            }
        });
        BotonAlisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAlisarActionPerformed(evt);
            }
        });
        jToolBar2.add(BotonAlisar);

        Grosor.setToolTipText("grosor");
        Grosor.setValue(0);
        Grosor.setPreferredSize(new java.awt.Dimension(75, 20));
        Grosor.setRequestFocusEnabled(false);
        Grosor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                GrosorStateChanged(evt);
            }
        });
        jToolBar2.add(Grosor);
        jToolBar2.add(jSeparator2);

        Volcado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos2/volcado.png"))); // NOI18N
        Volcado.setFocusable(false);
        Volcado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Volcado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Volcado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolcadoActionPerformed(evt);
            }
        });
        jToolBar2.add(Volcado);
        jToolBar2.add(jSeparator9);

        PlayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/play.png"))); // NOI18N
        SonidoButtongroup.add(PlayButton);
        PlayButton.setFocusable(false);
        PlayButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PlayButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        PlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayButtonActionPerformed(evt);
            }
        });
        jToolBar2.add(PlayButton);

        StopButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/stop.png"))); // NOI18N
        SonidoButtongroup.add(StopButton);
        StopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopButtonActionPerformed(evt);
            }
        });
        jToolBar2.add(StopButton);

        jToolBar2.add(AudioList);
        jToolBar2.add(jSeparator11);

        GrabarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/record.png"))); // NOI18N
        GrabarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrabarButtonActionPerformed(evt);
            }
        });
        jToolBar2.add(GrabarButton);

        PanelToolBar.add(jToolBar2);

        getContentPane().add(PanelToolBar, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1162, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );

        getContentPane().add(escritorio, java.awt.BorderLayout.CENTER);

        PanelAbajo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelAbajo.setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos2/brillo.png"))); // NOI18N
        jToolBar1.add(jLabel1);

        BrilloSlider.setMaximum(255);
        BrilloSlider.setMinimum(-255);
        BrilloSlider.setToolTipText("brillo");
        BrilloSlider.setValue(0);
        BrilloSlider.setFocusTraversalPolicyProvider(true);
        BrilloSlider.setPreferredSize(new java.awt.Dimension(75, 20));
        BrilloSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BrilloSliderStateChanged(evt);
            }
        });
        BrilloSlider.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BrilloSliderFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                BrilloSliderFocusLost(evt);
            }
        });
        jToolBar1.add(BrilloSlider);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos2/contraste.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(20, 20));
        jToolBar1.add(jLabel2);

        ContrasteSlider.setToolTipText("contraste");
        ContrasteSlider.setPreferredSize(new java.awt.Dimension(75, 20));
        ContrasteSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ContrasteSliderStateChanged(evt);
            }
        });
        ContrasteSlider.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ContrasteSliderFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ContrasteSliderFocusLost(evt);
            }
        });
        jToolBar1.add(ContrasteSlider);
        jToolBar1.add(jSeparator4);

        Mascara.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Media", "Binomial", "Enfoque", "Relieve", "Laplacaino", "Emborronamiento Iluminado", "Emborronamiento Iluminado 5x5" }));
        Mascara.setPreferredSize(new java.awt.Dimension(140, 22));
        Mascara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MascaraActionPerformed(evt);
            }
        });
        jToolBar1.add(Mascara);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos2/cometa.png"))); // NOI18N
        jToolBar1.add(jLabel3);

        CometaSlider.setMaximum(50);
        CometaSlider.setMinimum(1);
        CometaSlider.setToolTipText("cometa");
        CometaSlider.setValue(1);
        CometaSlider.setPreferredSize(new java.awt.Dimension(75, 20));
        CometaSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CometaSliderStateChanged(evt);
            }
        });
        CometaSlider.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CometaSliderFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CometaSliderFocusLost(evt);
            }
        });
        jToolBar1.add(CometaSlider);
        jToolBar1.add(jSeparator5);

        ContrasteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos2/contraste2.png"))); // NOI18N
        ContrasteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContrasteButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(ContrasteButton);

        OscurecerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos2/ocurecer.png"))); // NOI18N
        OscurecerButton.setFocusable(false);
        OscurecerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        OscurecerButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        OscurecerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OscurecerButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(OscurecerButton);

        IluminarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos2/iluminar.png"))); // NOI18N
        IluminarButton.setFocusable(false);
        IluminarButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IluminarButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        IluminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IluminarButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(IluminarButton);

        negativoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos2/operador1.png"))); // NOI18N
        negativoButton.setFocusable(false);
        negativoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        negativoButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        negativoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negativoButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(negativoButton);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos2/operador2.png"))); // NOI18N
        jToolBar1.add(jLabel4);

        rotateSlider.setMaximum(360);
        rotateSlider.setValue(0);
        rotateSlider.setPreferredSize(new java.awt.Dimension(50, 20));
        rotateSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rotateSliderStateChanged(evt);
            }
        });
        rotateSlider.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rotateSliderFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rotateSliderFocusLost(evt);
            }
        });
        jToolBar1.add(rotateSlider);

        TLinealSlider.setMaximum(255);
        TLinealSlider.setValue(0);
        TLinealSlider.setPreferredSize(new java.awt.Dimension(50, 20));
        TLinealSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TLinealSliderStateChanged(evt);
            }
        });
        TLinealSlider.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TLinealSliderFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TLinealSliderFocusLost(evt);
            }
        });
        jToolBar1.add(TLinealSlider);
        jToolBar1.add(jSeparator6);

        Rotar180Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos2/rotar180.png"))); // NOI18N
        Rotar180Button.setFocusable(false);
        Rotar180Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Rotar180Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Rotar180Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rotar180ButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(Rotar180Button);

        MasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos2/mas.png"))); // NOI18N
        MasButton.setFocusable(false);
        MasButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MasButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(MasButton);

        menosButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos2/menos.png"))); // NOI18N
        menosButton.setFocusable(false);
        menosButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menosButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(menosButton);
        jToolBar1.add(jSeparator7);

        ShowBandasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos2/bandas.png"))); // NOI18N
        ShowBandasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowBandasButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(ShowBandasButton);

        seleccionEspacioCOLOR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sRGB", "YCC", "GREY" }));
        seleccionEspacioCOLOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionEspacioCOLORActionPerformed(evt);
            }
        });
        jToolBar1.add(seleccionEspacioCOLOR);
        jToolBar1.add(jSeparator8);

        CombinarBandasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos2/combinar.png"))); // NOI18N
        CombinarBandasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombinarBandasButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(CombinarBandasButton);

        tintarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos2/tintar.png"))); // NOI18N
        tintarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tintarButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(tintarButton);

        sepiaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos2/sepia.png"))); // NOI18N
        sepiaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sepiaButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(sepiaButton);

        ecualizarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos2/ecualizar.png"))); // NOI18N
        ecualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecualizarButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(ecualizarButton);

        rojoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos2/rojo.png"))); // NOI18N
        rojoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rojoButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(rojoButton);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos2/posterizar.png"))); // NOI18N
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jToolBar1.add(jLabel5);

        posterizarSlider.setMaximum(20);
        posterizarSlider.setMinimum(2);
        posterizarSlider.setValue(2);
        posterizarSlider.setPreferredSize(new java.awt.Dimension(50, 20));
        posterizarSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                posterizarSliderStateChanged(evt);
            }
        });
        posterizarSlider.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                posterizarSliderFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                posterizarSliderFocusLost(evt);
            }
        });
        jToolBar1.add(posterizarSlider);

        ColorReto1Button.setBackground(new java.awt.Color(255, 0, 0));
        ColorReto1Button.setActionCommand("color");
        ColorReto1Button.setFocusable(false);
        ColorReto1Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ColorReto1Button.setOpaque(true);
        ColorReto1Button.setPreferredSize(new java.awt.Dimension(10, 10));
        ColorReto1Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ColorReto1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorReto1ButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(ColorReto1Button);

        retoFinalslider.setMaximum(360);
        retoFinalslider.setValue(0);
        retoFinalslider.setPreferredSize(new java.awt.Dimension(50, 20));
        retoFinalslider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                retoFinalsliderStateChanged(evt);
            }
        });
        retoFinalslider.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                retoFinalsliderFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                retoFinalsliderFocusLost(evt);
            }
        });
        jToolBar1.add(retoFinalslider);

        ColorReto2Button.setBackground(new java.awt.Color(0, 0, 255));
        ColorReto2Button.setActionCommand("color");
        ColorReto2Button.setFocusable(false);
        ColorReto2Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ColorReto2Button.setOpaque(true);
        ColorReto2Button.setPreferredSize(new java.awt.Dimension(10, 10));
        ColorReto2Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ColorReto2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorReto2ButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(ColorReto2Button);

        PanelAbajo.add(jToolBar1, java.awt.BorderLayout.LINE_START);

        jPanel1.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(247, 10));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        PanelAbajo.add(jPanel1, java.awt.BorderLayout.CENTER);

        PanelEstado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelEstado.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        LabelEstado.setText("Barra de estado");
        PanelEstado.add(LabelEstado);

        PanelAbajo.add(PanelEstado, java.awt.BorderLayout.SOUTH);

        getContentPane().add(PanelAbajo, java.awt.BorderLayout.SOUTH);

        menuArchivo.setText("Archivo");

        MenuNuevo.setText("Nuevo");
        MenuNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuNuevoActionPerformed(evt);
            }
        });
        menuArchivo.add(MenuNuevo);

        MenuAbrir.setText("Abrir");
        MenuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAbrirActionPerformed(evt);
            }
        });
        menuArchivo.add(MenuAbrir);

        MenuGuardar.setText("Guardar");
        MenuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGuardarActionPerformed(evt);
            }
        });
        menuArchivo.add(MenuGuardar);

        MenuAbrirAudio.setText("Abrir Audio");
        MenuAbrirAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAbrirAudioActionPerformed(evt);
            }
        });
        menuArchivo.add(MenuAbrirAudio);

        jMenuBar2.add(menuArchivo);

        menuImagen.setText("Imagen");

        RescaleOpMENU.setText("RescaleOp");
        RescaleOpMENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RescaleOpMENUActionPerformed(evt);
            }
        });
        menuImagen.add(RescaleOpMENU);

        ConvolveOpMENU.setText("ConvolveOp");
        ConvolveOpMENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvolveOpMENUActionPerformed(evt);
            }
        });
        menuImagen.add(ConvolveOpMENU);

        AffineTransformOpMENU.setText("AffineTransformOp");
        AffineTransformOpMENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AffineTransformOpMENUActionPerformed(evt);
            }
        });
        menuImagen.add(AffineTransformOpMENU);

        LookupOpMENU.setText("LookupOp");
        LookupOpMENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LookupOpMENUActionPerformed(evt);
            }
        });
        menuImagen.add(LookupOpMENU);

        reto1.setText("Transformacion Lineal");
        reto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reto1ActionPerformed(evt);
            }
        });
        menuImagen.add(reto1);

        reto2.setText("Oscurecer zonas claras");
        reto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reto2ActionPerformed(evt);
            }
        });
        menuImagen.add(reto2);

        BandCombineOpMENU.setText("BandCombineOp");
        BandCombineOpMENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BandCombineOpMENUActionPerformed(evt);
            }
        });
        menuImagen.add(BandCombineOpMENU);

        ColorConvertOpMENU.setText("ColorConvertOp");
        ColorConvertOpMENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorConvertOpMENUActionPerformed(evt);
            }
        });
        menuImagen.add(ColorConvertOpMENU);

        jMenuBar2.add(menuImagen);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNuevoActionPerformed
        VentanaInterna vi = new VentanaInterna();
        escritorio.add(vi);
        vi.setVisible(true);
        BufferedImage img;
        img = new BufferedImage(500,500,BufferedImage.TYPE_INT_RGB);
        Graphics2D g2d = img.createGraphics();
        g2d.setColor(Color.WHITE);
        g2d.fillRect(0, 0, img.getWidth(), img.getHeight());
        g2d.dispose();
        vi.getLienzo2D().setImg(img);
    }//GEN-LAST:event_MenuNuevoActionPerformed

    private void MenuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGuardarActionPerformed
        VentanaInterna vi=(VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getPaintedImage();
            if (img != null) {
                JFileChooser dlg = new JFileChooser();
                int resp = dlg.showSaveDialog(this);
                if (resp == JFileChooser.APPROVE_OPTION) {
                    try {
                        File f = dlg.getSelectedFile();
                        ImageIO.write(img, "jpg", f);
                        vi.setTitle(f.getName());
                    } catch (Exception ex) {
                        System.err.println("Error al guardar la imagen");
                    }
                }
            }
        }
    }//GEN-LAST:event_MenuGuardarActionPerformed

    private void BotonLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLineaActionPerformed
        if(this.getSelectedLienzo() != null)    this.getSelectedLienzo().setHerramienta(Linea);
        LabelEstado.setText("Dibujando Linea");
    }//GEN-LAST:event_BotonLineaActionPerformed

    private void BotonRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRectanguloActionPerformed
        if(this.getSelectedLienzo() != null)    this.getSelectedLienzo().setHerramienta(Rectangulo);
        LabelEstado.setText("Dibujando Rectangulo");
    }//GEN-LAST:event_BotonRectanguloActionPerformed

    private void BotonElipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonElipseActionPerformed
        if(this.getSelectedLienzo() != null)    this.getSelectedLienzo().setHerramienta(Elipse);
        LabelEstado.setText("Dibujando Elipse");
    }//GEN-LAST:event_BotonElipseActionPerformed

    private void BotonFantasmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFantasmaActionPerformed
        if(this.getSelectedLienzo() != null)    this.getSelectedLienzo().setHerramienta(Fantasma);
        LabelEstado.setText("Dibujando Fantasma");
    }//GEN-LAST:event_BotonFantasmaActionPerformed

    private void BotonRellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRellenoActionPerformed
        if(this.getSelectedLienzo() != null){
            this.getSelectedLienzo().setRelleno(this.BotonRelleno.isSelected());
            this.getSelectedLienzo().actualizarSelectedFigure();
        } 
    }//GEN-LAST:event_BotonRellenoActionPerformed

    private void BotonColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonColorActionPerformed
        Color nuevoColor = JColorChooser.showDialog(null, "Elige un color", null);
        if (nuevoColor != null) {
            BotonColor.setBackground(nuevoColor);
            if(this.getSelectedLienzo() != null){
                this.getSelectedLienzo().setColor(nuevoColor);
                this.getSelectedLienzo().actualizarSelectedFigure();
            }
        }
    }//GEN-LAST:event_BotonColorActionPerformed

    private void BotonMoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMoverActionPerformed
        if(this.getSelectedLienzo() != null)    this.getSelectedLienzo().setHerramienta(Arrastrar);
        LabelEstado.setText("Arrastar selecionado");
        if(this.getSelectedLienzo() != null)    this.getSelectedLienzo().setMover(this.BotonMover.isSelected());
    }//GEN-LAST:event_BotonMoverActionPerformed

    private void GrosorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_GrosorStateChanged
        Stroke trazo = new BasicStroke(this.Grosor.getValue());
        if(this.getSelectedLienzo() != null){
            this.getSelectedLienzo().setTrazo(trazo);
            this.getSelectedLienzo().actualizarSelectedFigure();
        }        
    }//GEN-LAST:event_GrosorStateChanged

    private void BotonAlisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAlisarActionPerformed
        if(this.getSelectedLienzo() != null){
            this.getSelectedLienzo().setAlisado(this.BotonAlisar.isSelected());
            this.getSelectedLienzo().actualizarSelectedFigure();
        }        
    }//GEN-LAST:event_BotonAlisarActionPerformed

    private void BotonTransparenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTransparenciaActionPerformed
        if(this.getSelectedLienzo() != null){
            this.getSelectedLienzo().setTransparencia(this.BotonTransparencia.isSelected());
            this.getSelectedLienzo().actualizarSelectedFigure();
        }        
    }//GEN-LAST:event_BotonTransparenciaActionPerformed

    private void BotonMoverStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BotonMoverStateChanged
        if(this.getSelectedLienzo() != null)    this.getSelectedLienzo().setMover(this.BotonMover.isSelected());
    }//GEN-LAST:event_BotonMoverStateChanged

    private void BotonTransparenciaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BotonTransparenciaStateChanged
        if(this.getSelectedLienzo() != null)    this.getSelectedLienzo().setTransparencia(this.BotonTransparencia.isSelected());
    }//GEN-LAST:event_BotonTransparenciaStateChanged

    private void BotonAlisarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BotonAlisarStateChanged
        if(this.getSelectedLienzo() != null)    this.getSelectedLienzo().setAlisado(this.BotonAlisar.isSelected());
    }//GEN-LAST:event_BotonAlisarStateChanged

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        MenuNuevoActionPerformed(evt);
    }//GEN-LAST:event_NuevoActionPerformed

    private void AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirActionPerformed
        MenuAbrirActionPerformed(evt);
    }//GEN-LAST:event_AbrirActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        MenuGuardarActionPerformed(evt);
    }//GEN-LAST:event_GuardarActionPerformed

    private void VolcadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolcadoActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            vi.getLienzo2D().volcarFigura();
        }
    }//GEN-LAST:event_VolcadoActionPerformed

    private void MenuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAbrirActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if( resp == JFileChooser.APPROVE_OPTION) {
            try{
                File f = dlg.getSelectedFile();
                BufferedImage img = ImageIO.read(f);
                VentanaInterna vi = new VentanaInterna();
                vi.getLienzo2D().setImg(img);
                this.escritorio.add(vi);
                vi.setTitle(f.getName());
                vi.setVisible(true);
            }catch(Exception ex){
                System.err.println("Error al leer la imagen");
            }
        }
    }//GEN-LAST:event_MenuAbrirActionPerformed

    private void RescaleOpMENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RescaleOpMENUActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImg();
            if(img!=null){
                try{
                    RescaleOp rop = new RescaleOp(1.0F, 100.0F, null);
                    rop.filter(img, img);
                    vi.getLienzo2D().repaint();
                } catch(IllegalArgumentException e){
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_RescaleOpMENUActionPerformed

    private void ConvolveOpMENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvolveOpMENUActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImg();
            if(img!=null){
                try{
                    float filtro[] = {0.1f, 0.1f, 0.1f, 0.1f, 0.2f, 0.1f,0.1f, 0.1f, 0.1f};
                    Kernel k = new Kernel(3, 3, filtro);
                    ConvolveOp cop = new ConvolveOp(k);
                    BufferedImage imgdest = cop.filter(img, null);
                    vi.getLienzo2D().setImg(imgdest);
                    vi.getLienzo2D().repaint();
                } catch(IllegalArgumentException e){
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_ConvolveOpMENUActionPerformed

    private void BrilloSliderFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BrilloSliderFocusGained
        VentanaInterna vi = (VentanaInterna)(escritorio.getSelectedFrame());
        if(vi!=null){
            ColorModel cm = vi.getLienzo2D().getImg().getColorModel();
            WritableRaster raster = vi.getLienzo2D().getImg().copyData(null);
            boolean alfaPre = vi.getLienzo2D().getImg().isAlphaPremultiplied();
            imgFuente = new BufferedImage(cm,raster,alfaPre,null);
        }
    }//GEN-LAST:event_BrilloSliderFocusGained

    private void BrilloSliderFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BrilloSliderFocusLost
        imgFuente = null;
    }//GEN-LAST:event_BrilloSliderFocusLost

    private void BrilloSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BrilloSliderStateChanged
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImg();
            if(img!=null){
                try{
                    // Obtener el valor del deslizador de brillo
                    float brilloValue = this.BrilloSlider.getValue();

                    RescaleOp rop = new RescaleOp(1.0F, brilloValue, null);
                    rop.filter(imgFuente, img);
                    vi.getLienzo2D().repaint();
                } catch(IllegalArgumentException e){
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_BrilloSliderStateChanged

    private void ContrasteSliderFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ContrasteSliderFocusGained
        VentanaInterna vi = (VentanaInterna)(escritorio.getSelectedFrame());
        if(vi!=null){
            ColorModel cm = vi.getLienzo2D().getImg().getColorModel();
            WritableRaster raster = vi.getLienzo2D().getImg().copyData(null);
            boolean alfaPre = vi.getLienzo2D().getImg().isAlphaPremultiplied();
            imgFuente = new BufferedImage(cm,raster,alfaPre,null);
        }
    }//GEN-LAST:event_ContrasteSliderFocusGained

    private void ContrasteSliderFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ContrasteSliderFocusLost
        imgFuente = null;
    }//GEN-LAST:event_ContrasteSliderFocusLost

    private void ContrasteSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ContrasteSliderStateChanged
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImg();
            if(img!=null){
                try{
                    // Obtener el valor del deslizador de brillo
                    float contrasteValue = this.ContrasteSlider.getValue() / 20.0F;

                    RescaleOp rop = new RescaleOp(contrasteValue, 0.0F, null);
                    rop.filter(imgFuente, img);
                    vi.getLienzo2D().repaint();
                } catch(IllegalArgumentException e){
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_ContrasteSliderStateChanged

    private void MascaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MascaraActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage image = vi.getLienzo2D().getImg();
            Kernel k = getKernel(this.Mascara.getSelectedIndex());
            if(image != null && k != null){
                try{
                    ConvolveOp cop = new ConvolveOp(k);
                    BufferedImage imgdest = cop.filter(image, null);
                    vi.getLienzo2D().setImg(imgdest);
                    vi.getLienzo2D().repaint();
                } catch(IllegalArgumentException e){
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_MascaraActionPerformed

    private void CometaSliderFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CometaSliderFocusGained
        VentanaInterna vi = (VentanaInterna)(escritorio.getSelectedFrame());
        if(vi!=null){
            ColorModel cm = vi.getLienzo2D().getImg().getColorModel();
            WritableRaster raster = vi.getLienzo2D().getImg().copyData(null);
            boolean alfaPre = vi.getLienzo2D().getImg().isAlphaPremultiplied();
            imgFuente = new BufferedImage(cm,raster,alfaPre,null);
        }
    }//GEN-LAST:event_CometaSliderFocusGained

    private void CometaSliderFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CometaSliderFocusLost
        imgFuente = null;
    }//GEN-LAST:event_CometaSliderFocusLost

    private void CometaSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CometaSliderStateChanged
        VentanaInterna vi = (VentanaInterna)(escritorio.getSelectedFrame());
        if(vi!=null){
            BufferedImage image = vi.getLienzo2D().getImg();
            if (image != null) {
                try {
                    // Obtener el valor del deslizador de tamaño de máscara
                    int mascaraSize = this.CometaSlider.getValue();

                    // Crear la máscara del filtro de emborronamiento "cometa"
                    float[] kernel = createCometBlurKernel(mascaraSize);
                    Kernel k = new Kernel(kernel.length, 1, kernel);

                    // Aplicar el filtro de convolución a la imagen
                    ConvolveOp cop = new ConvolveOp(k, java.awt.image.ConvolveOp.EDGE_NO_OP, null);
                    cop.filter(imgFuente, image);
                    vi.getLienzo2D().repaint();

                    // Mostrar en consola el valor de la máscara aplicada
                    System.out.println("Tamaño de la máscara para emborronamiento cometa: " + mascaraSize);
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_CometaSliderStateChanged

    private void AffineTransformOpMENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AffineTransformOpMENUActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
         if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImg();
            if(img!=null){
                try{
                    AffineTransform at = AffineTransform.getScaleInstance(1.5,1.5);
                    AffineTransformOp atop = new AffineTransformOp(at,null);
                    BufferedImage imgdest = atop.filter(img, null);
                    vi.getLienzo2D().setImg(imgdest);
                    vi.getLienzo2D().repaint();
                } catch(IllegalArgumentException e){
                System.err.println(e.getLocalizedMessage());
                }
            }
         }
    }//GEN-LAST:event_AffineTransformOpMENUActionPerformed

    private void LookupOpMENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LookupOpMENUActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
         if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImg();
            if(img!=null){
                try{
                    byte funcionT[] = new byte[256];
                    for (int x=0; x<256; x++)
                     funcionT[x] = (byte)(255-x); // Negativo
                    ByteLookupTable tabla = new ByteLookupTable(0, funcionT);
                    LookupOp lop = new LookupOp(tabla, null);
                    BufferedImage imgdest = lop.filter(img, null);
                    vi.getLienzo2D().setImg(imgdest);
                    vi.getLienzo2D().repaint();
                } catch(IllegalArgumentException e){
                System.err.println(e.getLocalizedMessage());
                }
            }
         }
    }//GEN-LAST:event_LookupOpMENUActionPerformed

    private void ContrasteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContrasteButtonActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
         if (vi != null) {
             BufferedImage img = vi.getLienzo2D().getImg();
            try{
                int type = LookupTableProducer.TYPE_SFUNCION;
                LookupTable lt = LookupTableProducer.createLookupTable(type);
                LookupOp lop = new LookupOp(lt, null);
                lop.filter( img , img); // Imagen origen y destino iguales
                vi. getLienzo2D().repaint();
            } catch(IllegalArgumentException e){
            System.err.println(e.getLocalizedMessage());
            }
         }
    }//GEN-LAST:event_ContrasteButtonActionPerformed

    private void OscurecerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OscurecerButtonActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
         if (vi != null) {
             BufferedImage img = vi.getLienzo2D().getImg();
            try{
                int type = LookupTableProducer.TYPE_POWER;
                LookupTable lt = LookupTableProducer.createLookupTable(type);
                LookupOp lop = new LookupOp(lt, null);
                lop.filter( img , img); // Imagen origen y destino iguales
                vi. getLienzo2D().repaint();
            } catch(IllegalArgumentException e){
            System.err.println(e.getLocalizedMessage());
            }
         }
    }//GEN-LAST:event_OscurecerButtonActionPerformed

    private void IluminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IluminarButtonActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
         if (vi != null) {
             BufferedImage img = vi.getLienzo2D().getImg();
            try{
                int type = LookupTableProducer.TYPE_LOGARITHM;
                LookupTable lt = LookupTableProducer.createLookupTable(type);
                LookupOp lop = new LookupOp(lt, null);
                lop.filter( img , img); // Imagen origen y destino iguales
                vi. getLienzo2D().repaint();
            } catch(IllegalArgumentException e){
            System.err.println(e.getLocalizedMessage());
            }
         }
    }//GEN-LAST:event_IluminarButtonActionPerformed

    private void negativoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negativoButtonActionPerformed
        reto2ActionPerformed(evt);
    }//GEN-LAST:event_negativoButtonActionPerformed

    private void Rotar180ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rotar180ButtonActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
         if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImg();
            if(img!=null){
                try{
                    double r = Math.toRadians(180);
                    Point p = new Point(img.getWidth()/2, img.getHeight()/2);
                    AffineTransform at = AffineTransform.getRotateInstance(r,p.x,p.y);
                    AffineTransformOp atop;
                    atop = new AffineTransformOp(at,AffineTransformOp.TYPE_BILINEAR);
                    BufferedImage imgdest = atop.filter(img, null);
                    vi.getLienzo2D().setImg(imgdest);
                    vi.getLienzo2D().repaint();
                } catch(IllegalArgumentException e){
                System.err.println(e.getLocalizedMessage());
                }
            }
         }
    }//GEN-LAST:event_Rotar180ButtonActionPerformed

    private void rotateSliderFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rotateSliderFocusGained
        VentanaInterna vi = (VentanaInterna)(escritorio.getSelectedFrame());
        if(vi!=null){
            this.imgFuente = vi.getLienzo2D().getImg();
        }
    }//GEN-LAST:event_rotateSliderFocusGained

    private void rotateSliderFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rotateSliderFocusLost
        imgFuente = null;
        this.rotateSlider.setValue(0);
    }//GEN-LAST:event_rotateSliderFocusLost

    private void rotateSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rotateSliderStateChanged
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
         if (vi != null) {
            if(imgFuente!=null){
                try{
                    double r = Math.toRadians(rotateSlider.getValue());
                    Point p = new Point(imgFuente.getWidth()/2, imgFuente.getHeight()/2);
                    AffineTransform at = AffineTransform.getRotateInstance(r,p.x,p.y);
                    AffineTransformOp atop;
                    atop = new AffineTransformOp(at,AffineTransformOp.TYPE_BILINEAR);
                    BufferedImage imgdest = atop.filter(imgFuente, null);
                    vi.getLienzo2D().setImg(imgdest);
                    vi.getLienzo2D().repaint();
                } catch(IllegalArgumentException e){
                System.err.println(e.getLocalizedMessage());
                }
            }
         }
    }//GEN-LAST:event_rotateSliderStateChanged

    private void MasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasButtonActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
         if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImg();
            if(img!=null){
                try{
                    double scaleFactor = 1.25;
                    AffineTransform at = AffineTransform.getScaleInstance(scaleFactor, scaleFactor);
                    
                    AffineTransformOp atop = new AffineTransformOp(at,AffineTransformOp.TYPE_BILINEAR);
                    BufferedImage imgdest = atop.filter(img, null);
                    vi.getLienzo2D().setImg(imgdest);
                    vi.getLienzo2D().repaint();
                } catch(IllegalArgumentException e){
                System.err.println(e.getLocalizedMessage());
                }
            }
         }
    }//GEN-LAST:event_MasButtonActionPerformed

    private void menosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosButtonActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
         if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImg();
            if(img!=null){
                try{
                    double scaleFactor = 0.75;
                    AffineTransform at = AffineTransform.getScaleInstance(scaleFactor, scaleFactor);
                    
                    AffineTransformOp atop = new AffineTransformOp(at,AffineTransformOp.TYPE_BILINEAR);
                    BufferedImage imgdest = atop.filter(img, null);
                    vi.getLienzo2D().setImg(imgdest);
                    vi.getLienzo2D().repaint();
                } catch(IllegalArgumentException e){
                System.err.println(e.getLocalizedMessage());
                }
            }
         }        
    }//GEN-LAST:event_menosButtonActionPerformed

    private void reto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reto1ActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
         if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImg();
            if(img!=null){
                try{
                    byte[] functionT = new byte[256];
                    int controlPoint = 128; 

                    for (int x = 0; x < 256; x++) {
                      if (x < controlPoint) {
                        functionT[x] = (byte) (x * controlPoint / 128); // Linear for x < 128
                      } else if (x == controlPoint) {
                        functionT[x] = (byte) controlPoint; 
                      } else {
                        int newX = (255 - controlPoint) * (x - controlPoint) / 127 + controlPoint;
                        functionT[x] = (byte) Math.min(newX, 255); 
                      }
                    }
                    ByteLookupTable tabla = new ByteLookupTable(0, functionT);
                    LookupOp lop = new LookupOp(tabla, null);
                    BufferedImage imgdest = lop.filter(img, null);
                    vi.getLienzo2D().setImg(imgdest);
                    vi.getLienzo2D().repaint();
                } catch(IllegalArgumentException e){
                System.err.println(e.getLocalizedMessage());
                }
            }
         }
    }//GEN-LAST:event_reto1ActionPerformed

    private void reto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reto2ActionPerformed

        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
           BufferedImage img = vi.getLienzo2D().getImg();
           if(img!=null){
               try{
                    double m = 128; //umbral
                    
                    byte[] lookupTable = new byte[256];
                    for (int i = 0; i < 256; i++) {
                        if (i < m) {
                            lookupTable[i] = (byte) i;
                        } else {
                            int v = (int)(Math.pow((i- m), 2) / (double) m+m);
                            lookupTable[i] = (byte) Math.max(0, Math.min(255, v));
                        }
                    }
                    
                    ByteLookupTable tabla = new ByteLookupTable(0, lookupTable);
                    LookupOp lop = new LookupOp(tabla, null);
                    BufferedImage imgdest = lop.filter(img, null);
                    vi.getLienzo2D().setImg(imgdest);
                    vi.getLienzo2D().repaint();
               } catch(IllegalArgumentException e){
               System.err.println(e.getLocalizedMessage());
               }
           }
        }
    }//GEN-LAST:event_reto2ActionPerformed

    private void ShowBandasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowBandasButtonActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImg();
            String titulo = vi.getTitle();
           if(img!=null){
               for (int i = 0; i < img.getRaster().getNumBands(); i++) {
                   BufferedImage imgBanda = getImageBand(img,i);
                   vi = new VentanaInterna(vi);
                   vi.setTitle(titulo + " (Bandas  "+ i +")");
                   vi.getLienzo2D().setImg(imgBanda);
                   escritorio.add(vi);
                   vi.setVisible(true);
               }
           }
        }
    }//GEN-LAST:event_ShowBandasButtonActionPerformed

    private void CopiarYdesplazarVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CopiarYdesplazarVentanaActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImg();
            if(img!=null){
                try{
                    VentanaInterna copia = new VentanaInterna(vi);
                    escritorio.add(copia);
                    copia.setVisible(true);
                } catch(IllegalArgumentException e){
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_CopiarYdesplazarVentanaActionPerformed

    private void BandCombineOpMENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BandCombineOpMENUActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImg();
            if(img!=null){
                try{
                    float[][] matriz = {{1.0F, 0.0F, 0.0F},{0.0F, 0.0F, 1.0F},{0.0F, 1.0F, 0.0F}};
                    BandCombineOp bcop = new BandCombineOp(matriz, null);
                    bcop.filter(img.getRaster(), img.getRaster());
                    vi.getLienzo2D().repaint();
                } catch(IllegalArgumentException e){
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_BandCombineOpMENUActionPerformed

    private void ColorConvertOpMENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorConvertOpMENUActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImg();
            if(img!=null){
                try{
                    ColorSpace cs = ColorSpace.getInstance(ColorSpace.CS_PYCC);
                    ColorConvertOp op = new ColorConvertOp(cs, null);
                    BufferedImage imgdest = op.filter(img,null);
                    vi.getLienzo2D().setImg(imgdest);
                    vi.getLienzo2D().repaint();
                } catch(IllegalArgumentException e){
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_ColorConvertOpMENUActionPerformed

    private void seleccionEspacioCOLORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionEspacioCOLORActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImg();
            if(img!=null){
                ColorSpace cs = null;
                int seleccion = this.seleccionEspacioCOLOR.getSelectedIndex();
                BufferedImage imgdest = null; 
                String nombreEspacioColor = null;
                
                try {
                    // Determinar el espacio de color seleccionado
                    switch(seleccion) {
                        case 0: // sRGB
                            cs = ColorSpace.getInstance(ColorSpace.CS_sRGB);
                            nombreEspacioColor = "sRGB";
                            break;
                        case 1: // YCC
                            cs = ColorSpace.getInstance(ColorSpace.CS_PYCC);
                            nombreEspacioColor = "YCC";
                            break;
                        case 2: // GREY
                            cs = ColorSpace.getInstance(ColorSpace.CS_GRAY);
                            nombreEspacioColor = "GREY";
                            break;
                        default:
                            break;
                    }

                    // Verificar si es necesario realizar la conversión
                    if (cs != null && !img.getColorModel().getColorSpace().equals(cs)) {
                        ColorConvertOp op = new ColorConvertOp(cs, null);
                        imgdest = op.filter(img, null);
                    } else {
                        // No es necesario realizar la conversión, mantener la imagen original
                        imgdest = img;
                    }

                    if (imgdest != null) {                      
                        // Mostrar la nueva imagen en una ventana interna
                        VentanaInterna nuevaVi = new VentanaInterna(vi);
                        nuevaVi.setTitle(vi.getTitle()+ "(" + nombreEspacioColor +")" );
                        nuevaVi.getLienzo2D().setImg(imgdest);
                        escritorio.add(nuevaVi);
                        nuevaVi.setVisible(true);
                    }
                } catch(IllegalArgumentException e){
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }    
    }//GEN-LAST:event_seleccionEspacioCOLORActionPerformed

    private void CombinarBandasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombinarBandasButtonActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImg();
            if(img!=null){
                try{
                    float[][] matriz = {{0.0F, 0.5F, 0.5F},{0.5F, 0.0F, 0.5F},{0.5F, 0.5F, 0.0F}};
                    BandCombineOp bcop = new BandCombineOp(matriz, null);
                    bcop.filter(img.getRaster(), img.getRaster());
                    vi.getLienzo2D().repaint();
                } catch(IllegalArgumentException e){
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_CombinarBandasButtonActionPerformed

    private void ColorReto1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorReto1ButtonActionPerformed
        Color nuevoColor = JColorChooser.showDialog(null, "Elige un color", null);
        if (nuevoColor != null) {
            ColorReto1Button.setBackground(nuevoColor);
        }
    }//GEN-LAST:event_ColorReto1ButtonActionPerformed

    private void ColorReto2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorReto2ButtonActionPerformed
        Color nuevoColor = JColorChooser.showDialog(null, "Elige un color", null);
        if (nuevoColor != null) {
            ColorReto2Button.setBackground(nuevoColor);
        }
    }//GEN-LAST:event_ColorReto2ButtonActionPerformed

    private void tintarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tintarButtonActionPerformed
        VentanaInterna vi = (VentanaInterna)(escritorio.getSelectedFrame());
        if(vi!=null){
            Color nuevoColor = JColorChooser.showDialog(null, "Elige un color", null);
            if (nuevoColor != null) {
                BufferedImage img = vi.getLienzo2D().getImg();
                if(img!=null){
                    try{
                        TintOp tintado = new TintOp(nuevoColor,0.5f);
                        BufferedImage imgdest = tintado.filter(img,img);
                        vi.getLienzo2D().setImg(imgdest);
                        vi.getLienzo2D().repaint();
                    } catch(IllegalArgumentException e){
                    System.err.println(e.getLocalizedMessage());
                    }
                }
            }
        }
    }//GEN-LAST:event_tintarButtonActionPerformed

    private void posterizarSliderFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_posterizarSliderFocusGained
        VentanaInterna vi = (VentanaInterna)(escritorio.getSelectedFrame());
        if(vi!=null){
            this.imgFuente = vi.getLienzo2D().getImg();
        }
    }//GEN-LAST:event_posterizarSliderFocusGained

    private void posterizarSliderFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_posterizarSliderFocusLost
        imgFuente = null;
    }//GEN-LAST:event_posterizarSliderFocusLost

    private void posterizarSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_posterizarSliderStateChanged
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
         if (vi != null) {
            if(imgFuente!=null){
                try{
                    PosterizarOP poster = new PosterizarOP(this.posterizarSlider.getValue());
                    BufferedImage imgdest = poster.filter(imgFuente, null);
                    vi.getLienzo2D().setImg(imgdest);
                    vi.getLienzo2D().repaint();
                } catch(IllegalArgumentException e){
                System.err.println(e.getLocalizedMessage());
                }
            }
         }
    }//GEN-LAST:event_posterizarSliderStateChanged

    private void retoFinalsliderFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_retoFinalsliderFocusGained
        VentanaInterna vi = (VentanaInterna)(escritorio.getSelectedFrame());
        if(vi!=null){
            this.imgFuente = vi.getLienzo2D().getImg();
        }
    }//GEN-LAST:event_retoFinalsliderFocusGained

    private void retoFinalsliderFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_retoFinalsliderFocusLost
        imgFuente = null;
    }//GEN-LAST:event_retoFinalsliderFocusLost

    private void retoFinalsliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_retoFinalsliderStateChanged
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
         if (vi != null) {
            if(imgFuente!=null){
                try{
                    RetoOp retopo = new RetoOp(ColorReto1Button.getBackground(),ColorReto2Button.getBackground(),this.retoFinalslider.getValue());
                    BufferedImage imgdest = retopo.filter(imgFuente, null);
                    vi.getLienzo2D().setImg(imgdest);
                    vi.getLienzo2D().repaint();
                } catch(IllegalArgumentException e){
                System.err.println(e.getLocalizedMessage());
                }
            }
         }
    }//GEN-LAST:event_retoFinalsliderStateChanged

    private void sepiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sepiaButtonActionPerformed
        VentanaInterna vi = (VentanaInterna)(escritorio.getSelectedFrame());
        if(vi!=null){
            BufferedImage img = vi.getLienzo2D().getImg();
            if(img!=null){
                try{
                    SepiaOp sepia = new SepiaOp();
                    BufferedImage imgdest = sepia.filter(img,img);
                    vi.getLienzo2D().setImg(imgdest);
                    vi.getLienzo2D().repaint();
                } catch(IllegalArgumentException e){
                System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_sepiaButtonActionPerformed

    private void ecualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecualizarButtonActionPerformed
        VentanaInterna vi = (VentanaInterna)(escritorio.getSelectedFrame());
        if(vi!=null){
            BufferedImage img = vi.getLienzo2D().getImg();
            if(img!=null){
                try{
                    EqualizationOp ecualizacion = new EqualizationOp();
                    BufferedImage imgdest = ecualizacion.filter(img,img);
                    vi.getLienzo2D().setImg(imgdest);
                    vi.getLienzo2D().repaint();
                } catch(IllegalArgumentException e){
                System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_ecualizarButtonActionPerformed

    private void rojoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rojoButtonActionPerformed
        VentanaInterna vi = (VentanaInterna)(escritorio.getSelectedFrame());
        if(vi!=null){
            BufferedImage img = vi.getLienzo2D().getImg();
            if(img!=null){
                try{
                    RojoOp rojo = new RojoOp(20);
                    BufferedImage imgdest = rojo.filter(img,img);
                    vi.getLienzo2D().setImg(imgdest);
                    vi.getLienzo2D().repaint();
                } catch(IllegalArgumentException e){
                System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_rojoButtonActionPerformed

    private void MenuAbrirAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAbrirAudioActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if( resp == JFileChooser.APPROVE_OPTION) {
            try{
                File aux = dlg.getSelectedFile();
                File f = new File(aux.getAbsolutePath()){
                    @Override
                    public String toString(){
                        return this.getName();
                    }
                };
                this.AudioList.addItem(f);
                this.AudioList.setSelectedItem(f);
            }catch(Exception ex){
                System.err.println("Error al leer el archivo de audio");
            }
        }
    }//GEN-LAST:event_MenuAbrirAudioActionPerformed

    private void StopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopButtonActionPerformed
        if(player != null){
            player.stop();
            player = null;
        }
        if(recorder != null){
            recorder.stop();
            recorder = null;
        }
    }//GEN-LAST:event_StopButtonActionPerformed

    private void PlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayButtonActionPerformed
        File f = (File) this.AudioList.getSelectedItem();
        if(f != null){
            player = new SMClipPlayer(f);
            if(player != null){
                player.play();
            }           
        }
    }//GEN-LAST:event_PlayButtonActionPerformed

    private void GrabarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrabarButtonActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showSaveDialog(this);
        if( resp == JFileChooser.APPROVE_OPTION) {
            try{
                File f = dlg.getSelectedFile();
                recorder = new SMSoundRecorder(f);
                if (recorder != null){
                    recorder.record();
                }
            }catch(Exception ex){
                System.err.println("Error al leer el archivo de audio");
            }
        }
    }//GEN-LAST:event_GrabarButtonActionPerformed

    private void TLinealSliderFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TLinealSliderFocusGained
        VentanaInterna vi = (VentanaInterna)(escritorio.getSelectedFrame());
        if(vi!=null){
            this.imgFuente = vi.getLienzo2D().getImg();
        }
    }//GEN-LAST:event_TLinealSliderFocusGained

    private void TLinealSliderFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TLinealSliderFocusLost
        imgFuente = null;
    }//GEN-LAST:event_TLinealSliderFocusLost

    private int transformPixel(int x, int a, int controlPoint) {
        if (x < controlPoint) {
            return (a * x) / controlPoint;
        } else {
            return ((255 - a) * (x - controlPoint)) / 127 + a;
        }
    }
    
    private void TLinealSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TLinealSliderStateChanged
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
         if (vi != null) {
            if(imgFuente!=null){
                try{
                    double a = TLinealSlider.getValue(); // Get the slider value (a)

                   // int controlPoint = 128; 

                    byte[] fT = new byte[256];
                    for (int x = 0; x < 256; x++) {
                        if (x < 128) {
                            fT[x] = (byte) ((a * x) / (double) 128);
                        } else {
                            fT[x] = (byte) (((255 - a) * (x - 128)) / 127 + a);
                        }
                    }

                    ByteLookupTable tabla = new ByteLookupTable(0, fT);
                    LookupOp lop = new LookupOp(tabla, null);
                    BufferedImage imgdest = lop.filter(imgFuente, null);
        
                    vi.getLienzo2D().setImg(imgdest);
                    vi.getLienzo2D().repaint();
                } catch(IllegalArgumentException e){
                System.err.println(e.getLocalizedMessage());
                }
            }
         }
    }//GEN-LAST:event_TLinealSliderStateChanged

    class ManejadorAudio implements LineListener {
        @Override
        public void update(LineEvent event) {
            if (event.getType() == LineEvent.Type.START) {
                PlayButton.setEnabled(false);
            }
            if (event.getType() == LineEvent.Type.STOP) {
                PlayButton.setEnabled(true);
            }
            if (event.getType() == LineEvent.Type.CLOSE) {
            }
        }
   }

    
    public static LookupTable inverseSFunction(double m, double e) {
      // Validate input parameters (m and e)
      if (m < 0 || m > 255 || e <= 0) {
        throw new IllegalArgumentException("Invalid parameters: m must be between 0 and 255, and e must be greater than 0.");
      }

      // Calculate constants based on the inverted formula
      double invMin = 1.0 / (1.0 + Math.pow(m / 255.0, e)); // Inverted power term for brightening
      double K = 255.0 * invMin; // Adjusted K for efficient calculation

      // Create lookup table
      byte[] lt = new byte[256];
      for (int l = 0; l < 256; l++) {
        lt[l] = (byte) (K * Math.pow(m / (float) (l + 1), e)); // +1 to avoid division by zero
      }

      // Create and return lookup table
      ByteLookupTable slt = new ByteLookupTable(0, lt);
      return slt;
    }
    
    private float[] createCometBlurKernel(int size) {
        float[] kernel = new float[size];
        float sum = 0;

        // Fill the kernel with decreasing values
        for (int i = 0; i < size; i++) {
            kernel[i] = (float)(size - i);
            sum += kernel[i];
        }

        // Normalize the kernel
        for (int i = 0; i < size; i++) {
            kernel[i] /= sum;
        }       
        return kernel;
    }
    
    private Kernel getKernel(int seleccion){
        Kernel k = null;
         
        switch (seleccion) {
            case 0:
                k = KernelProducer.createKernel(KernelProducer.TYPE_MEDIA_3x3);
                break;
            case 1:
                k = KernelProducer.createKernel(KernelProducer.TYPE_BINOMIAL_3x3);
                break;
            case 2:
                k = KernelProducer.createKernel(KernelProducer.TYPE_ENFOQUE_3x3);
                break;
            case 3:
                k = KernelProducer.createKernel(KernelProducer.TYPE_RELIEVE_3x3);
                break;
            case 4:
                k = KernelProducer.createKernel(KernelProducer.TYPE_LAPLACIANA_3x3);
                break;
            case 5:
                float[] filtroIluminado = {
                    2.0f / 9.0f, 2.0f / 9.0f, 2.0f / 9.0f, 2.0f / 9.0f, 2.0f / 9.0f, 2.0f / 9.0f, 2.0f / 9.0f, 2.0f / 9.0f, 2.0f / 9.0f,
                };
                k = new Kernel(3,3,filtroIluminado);
                break;
                
            case 6:
                float[] filtroIluminado5x5 = {
                    1f/25f, 1f/25f, 1f/25f, 1f/25f, 1f/25f,
                    1f/25f, 2f/25f, 2f/25f, 2f/25f, 1f/25f,
                    1f/25f, 2f/25f, 3f/25f, 2f/25f, 1f/25f,
                    1f/25f, 2f/25f, 2f/25f, 2f/25f, 1f/25f,
                    1f/25f, 1f/25f, 1f/25f, 1f/25f, 1f/25f
                };
                
                k = new Kernel(5,5,filtroIluminado5x5);
                break;
            default:
                throw new AssertionError();
        }

        return k;
    }
    
    private BufferedImage getImageBand(BufferedImage img, int i) {
        ColorSpace cs = ColorSpace.getInstance(ColorSpace.CS_GRAY);
        ComponentColorModel cm = new ComponentColorModel(cs,false,false,Transparency.OPAQUE, DataBuffer.TYPE_BYTE);
        int  vband[] = {i};
        WritableRaster bRaster = (WritableRaster) img.getRaster().createWritableChild(0, 0, img.getWidth(), img.getHeight(), 0, 0, vband);
   
        return new BufferedImage (cm, bRaster, false, null);
                
        }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Abrir;
    private javax.swing.JMenuItem AffineTransformOpMENU;
    private javax.swing.JComboBox<File> AudioList;
    private javax.swing.JMenuItem BandCombineOpMENU;
    private javax.swing.JToggleButton BotonAlisar;
    private javax.swing.JButton BotonColor;
    private javax.swing.JToggleButton BotonElipse;
    private javax.swing.JToggleButton BotonFantasma;
    private javax.swing.JToggleButton BotonLinea;
    private javax.swing.JToggleButton BotonMover;
    private javax.swing.JToggleButton BotonRectangulo;
    private javax.swing.JToggleButton BotonRelleno;
    private javax.swing.JToggleButton BotonTransparencia;
    private javax.swing.JSlider BrilloSlider;
    private javax.swing.JMenuItem ColorConvertOpMENU;
    private javax.swing.JButton ColorReto1Button;
    private javax.swing.JButton ColorReto2Button;
    private javax.swing.JButton CombinarBandasButton;
    private javax.swing.JSlider CometaSlider;
    private javax.swing.JButton ContrasteButton;
    private javax.swing.JSlider ContrasteSlider;
    private javax.swing.JMenuItem ConvolveOpMENU;
    private javax.swing.JButton CopiarYdesplazarVentana;
    private javax.swing.JButton GrabarButton;
    private javax.swing.JSlider Grosor;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton IluminarButton;
    private javax.swing.JLabel LabelEstado;
    private javax.swing.JMenuItem LookupOpMENU;
    private javax.swing.JButton MasButton;
    private javax.swing.JComboBox<String> Mascara;
    private javax.swing.JMenuItem MenuAbrir;
    private javax.swing.JMenuItem MenuAbrirAudio;
    private javax.swing.JMenuItem MenuGuardar;
    private javax.swing.JMenuItem MenuNuevo;
    private javax.swing.JButton Nuevo;
    private javax.swing.JButton OscurecerButton;
    private javax.swing.JPanel PanelAbajo;
    private javax.swing.JPanel PanelEstado;
    private javax.swing.JPanel PanelToolBar;
    private javax.swing.JButton PlayButton;
    private javax.swing.JMenuItem RescaleOpMENU;
    private javax.swing.JButton Rotar180Button;
    private javax.swing.JButton ShowBandasButton;
    private javax.swing.ButtonGroup SonidoButtongroup;
    private javax.swing.JButton StopButton;
    private javax.swing.JSlider TLinealSlider;
    private javax.swing.JButton Volcado;
    private javax.swing.ButtonGroup colo;
    private javax.swing.JButton ecualizarButton;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JButton menosButton;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuImagen;
    private javax.swing.JButton negativoButton;
    private javax.swing.ButtonGroup paint;
    private javax.swing.JSlider posterizarSlider;
    private javax.swing.JMenuItem reto1;
    private javax.swing.JMenuItem reto2;
    private javax.swing.JSlider retoFinalslider;
    private javax.swing.JButton rojoButton;
    private javax.swing.JSlider rotateSlider;
    private javax.swing.JComboBox<String> seleccionEspacioCOLOR;
    private javax.swing.JButton sepiaButton;
    private javax.swing.JButton tintarButton;
    // End of variables declaration//GEN-END:variables


}
