package p9;


import sm.dsv.Imagen.PanelLienzo;

/**
 *
 * @author Diego
 */
public class VentanaInterna extends javax.swing.JInternalFrame {

    private PanelLienzo lienzo;

    /**
     * Creates new form VentanaInterna
     */
    public VentanaInterna() {
        super("Ventana Interna",
              true,   // resizable
              true,   // closable
              true,   // maximizable
              true);  // iconifiable
        
        initComponents();
        // Crea una instancia de Lienzo2D y añádela al centro de la ventana interna
        lienzo = new PanelLienzo();
        this.add(lienzo);

        // Establece el tamaño predeterminado de la ventana interna
        this.setSize(500, 500);
    }

    
    // Método para obtener el lienzo 2D
    public PanelLienzo getLienzo2D() {
        return lienzo;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
